### ISSUE TITLE
Broken links when JS disabled

### ISSUE THREAD

**Issue by Xowap** [nuxt/nuxtjs.org#1]
Great to see the doc online! Stumbled across a small issue which I think impacts SEO (and paranoïd users like myself):

**Step by step**

1. Disable Javascript in browser
2. Go to https://nuxtjs.org/
3. Click any relative link (like "Get Started")

**Currently**

The "Get Started" link will send me to https://guide/installation, while other relative links have similar effects

**Expected**

Links should have the same URLs as when JS is enabled (aka "https://nuxtjs.org/guide/installation" for the case of "Get Started")

**Comment by Atinux** [comment]
It's now fixed, we submitted an issue to vue-router about it: https://github.com/vuejs/vue-router/issues/983

Thanks for spotting it @Xowap

**Comment by Xowap** [comment]
:+1:

**Comment by LinusBorg** [comment]
@Atinux How did you fix it in this project?

**Comment by Atinux** [comment]
Hi @LinusBorg 

I fixed it in this commit: https://github.com/nuxt/nuxt.js/commit/a30ce76b0c7c5205c6be0b6abc92974534763cef
