### ISSUE TITLE
How to support ie

### ISSUE THREAD

**Issue by stchou** [nuxt/nuxtjs.org#10]
my project in ie can  not run

log said:

> You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html 
webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser: https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events#Tools 
SCRIPT5022: [vuex] vuex requires a Promise polyfill in this browser. 
vendor.bundle.js, 行44130 字符21

but，I don't kown the nustjs entry，where can I write

> require("babel-polyfill");

**Comment by alexchopin** [comment]
Hi, can you explain more about your issue?

**Comment by Atinux** [comment]
What version of IE do you have?

**Comment by davodaslanifakor** [comment]
@Atinux  may be i have ie 5

**Comment by Atinux** [comment]
Vue does not support ie5 so we cannot either @davodaslanifakor

**Comment by davodaslanifakor** [comment]
@Atinux so bad for iran pleas active this option
