### ISSUE TITLE
scss , @extend not working with @nuxt/vuetify

### ISSUE THREAD

**Issue by guruprasaad123** [nuxt/nuxtjs.org#100]
Am trying to extend a property , let's just say [.blue](https://vuetifyjs.com/style/colors) using [@extend](http://sass-lang.com/guide) in my nuxt project.And here's my Code.
```
<template>
<div class="pa-0">
<p class="is-active">
Hello Multiverse...!
</p>
</template>
<style lang="scss" scoped>
.is-active{
    @extend .blue;
}
</style>
```
It Gives me this Error.
```

Module build failed:
    @extend .blue;
           ^
      ".is-active" failed to @extend ".blue".
The selector ".blue" was not found.
Use "@extend .blue !optional" if the extend should be able to fail.
      in D:\workspace\@vue\nuxt-ssr\express-template\template\pages\home.vue (line 91, column 13)

 @ ./node_modules/vue-style-loader?{"sourceMap":true}!./node_modules/css-loader?{"minimize":true,"importLoaders":1,"sourceMap":true,"alias":{"/static":"D://workspace//@vue//nuxt-ssr//express-template//template//static","/assets":"D://workspace//@vue//nuxt-ssr//express-template//template//assets"}}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-66ca12f6","scoped":true,"hasInlineConfig":true}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./pages/home.vue 4:14-596 13:3-17:5 14:22-604
 @ ./pages/home.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=3000&path=/__webpack_hmr ./.nuxt/client.js
```
But , I know that .blue selector exists because I wrote this code and it works..
```
<template>
<div class="pa-0">
<p class="blue">
Hello Multiverse...!
</p>
</template>
<style lang="scss" scoped>

</style>
```
But , I can't understand why my first code did'nt execute but second one does. Hope we figure that out.

**Comment by gar1t** [comment]
I'm seeing the same behavior. A couple more observations:

- No error if the selector is defined in the style element using `@extend`
- Error still results in non-scoped styles

**Comment by guruprasaad123** [comment]
Can we provide  examples for the both? @gar1t .So that we can clearly understand.

**Comment by Atinux** [comment]
Hi

You need to use [style-resources](https://github.com/nuxt/nuxt.js/tree/dev/examples/style-resources) property so SCSS know what class you are talking about.

**Comment by Radiergummi** [comment]
@Atinux Stumbling across this now, don't really understand what's happening. Using the `style-resources` property in `nuxt.config.js` seems to be discouraged by now:
```
[ WARN ] Using styleResources without the @nuxtjs/style-resources is not suggested and can lead to severe 
         performance issues. Please use https://github.com/nuxt-community/style-resources-module
```

The suggested link has the following paragraph at the top of its Readme file:

> **Do not import actual styles.** Use this module only to import variables, mixins, functions (et cetera) as they won't exist in the actual build. Importing actual styles will include them in every component and will also make your build/HMR magnitudes slower. **Do not do this!**

Which sounds like this should explicitly _not_ be used to import Vuetify styles. Is there any recommended way to enable extending Vuetify classes? We use the typography classes for pretty much every text snippet in the app, and it would be a real pain to duplicate this...

**Comment by nicoagp** [comment]
Hi, some time ago I had the same issue and ended replacing all @extend .class which was annoying.

My undertanding is that using style-resources-module is only to be used to make scss files with variales, mixins, etc (but not actual classes) available across the nuxt project.

I think If I add a class (which I would like to extend) into style resources will work but it's absolutetly not recommended.

Any idea or alternative how to extend a class? for instance

_type.scss
.small-text {...}

component.vue
<sytle lang="scss">
  .something {
   @extend .small-text;
}

Thanks :)
