### ISSUE TITLE
Documentation for nuxt-link?

### ISSUE THREAD

**Issue by cfjedimaster** [nuxt/nuxtjs.org#102]
While I didn't read the docs 100% from start to finish, I do believe I hit a large percentage of it, and I don't see nuxt-link mentioned anywhere. I first saw it in this example (https://nuxtjs.org/examples/custom-routes). Is it documented anywhere? And if so, should it also be documented in the main routing docs?

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c83">#c83</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @cfjedimaster 

Actually it's documented over here: https://nuxtjs.org/api/components-nuxt-link

But I believe we should write about it into https://nuxtjs.org/guide/routing

I added the enhancement label :)
