### ISSUE TITLE
Convert images to SVG

### ISSUE THREAD

**Issue by patrickdaze** [nuxt/nuxtjs.org#104]
Going forwards I was thinking of converting the PNG images to SVG for the following reasons:
* it can be used as both a source and a display file
* resizable/vector/smaller filesize
* it could be inserted inline for translations

**Upgrade path:**

1. Convert [nuxt-schema.png](https://github.com/nuxt/nuxtjs.org/blob/master/static/nuxt-schema.png) to SVG (keep PNG for now)
2. Convert [nuxt-views-schema.png](https://github.com/nuxt/nuxtjs.org/blob/master/static/nuxt-views-schema.png) to SVG (keep PNG for now)
3. Update [all translations](https://github.com/nuxt/docs) to point to SVG instead of PNG
4. Delete [nuxt-schema.png](https://github.com/nuxt/nuxtjs.org/blob/master/static/nuxt-schema.png) and [nuxt-views-schema.png](https://github.com/nuxt/nuxtjs.org/blob/master/static/nuxt-views-schema.png) once all translations points to the new SVG
5. (future/optional) Add SVG inline in translations (for multilingual support)

An example of the SVG file that could be used: [nuxt-schema-svg-example.zip](https://github.com/nuxt/nuxtjs.org/files/1640813/nuxt-schema-svg-example.zip)

Anyone think this would be beneficial?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c99">#c99</a>)</em></sub></div>

**Comment by Atinux** [comment]
I do!
