### ISSUE TITLE
Missing command on Commands page

### ISSUE THREAD

**Issue by florian-lefebvre** [nuxt/nuxtjs.org#1049]
At [https://nuxtjs.org/docs/2.x/get-started/commands#development-environment](https://nuxtjs.org/docs/2.x/get-started/commands#development-environment), clicking on NPX shows the NPM command and clicking on NPM shows nothing.

**Comment by debs-obrien** [comment]
can you refresh and check or show me a screenshot as I am not seeing any NPX command on that page. thanks

**Comment by florian-lefebvre** [comment]
Yes it's gone, sorry for the inconvenience.
