### ISSUE TITLE
Consider reminding folks how to use Axios in async data doc

### ISSUE THREAD

**Issue by cfjedimaster** [nuxt/nuxtjs.org#105]
I'm new to Nuxt, but when I tried my first async data example and used code similar to the doc (https://nuxtjs.org/guide/async-data), I ran into an issue because Axios wasn't available. I fixed that by following the *later* docs on modules, but this may trip someone up. Or maybe it's just me. ;)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c95">#c95</a>)</em></sub></div>

**Comment by Atinux** [comment]
Updated [here](https://github.com/nuxt/docs/commit/34d77848ce57ece061b06fb85937d7501c4708c6), thanks @cfjedimaster :)
