### ISSUE TITLE
Documentation about asyncData, server-side modules, etc

### ISSUE THREAD

**Issue by cfjedimaster** [nuxt/nuxtjs.org#106]
Please forgive the somewhat vague title. I ran into an interesting issue that is directly related to my lack of understanding about some core Nuxt-ness (that's a word, honest), and I'm wondering if the docs could have helped a bit here.

Some context. I was looking at the docs for asyncData and it's use of axios. This worked for me, but I wanted to use request-promise instead. I'm more familiar with that library.

So I thought - just npm install it and use it in my component. I was able to, but I got errors with the `fs` dependency. After talking about it on Gitter and some searching (https://github.com/nuxt/nuxt.js/issues/1849), I think I have a fundamental misunderstanding of nuxt.

I thought that in it's "server" mode, it was a Node server. And that I could add any old module I wanted to. I also thought that asyncData() was completely server side. One of the things a user on chat said was that asyncData can actually run both on the server and the browser (that wasn't clear at all from the docs).

So... I guess I'm wrong. When running `npm run dev`, is it not a Node app like Express. Or maybe it is - but it has to be able to run both in the browser, and the server? I mean I know if I were to generate a SPA from it that request-promise wouldn't work, but I thought if I *didn't* do that and ran it as a server side app, then I'd be ok.

Does this make sense? And again, please forgive my ignorance.

**Comment by cfjedimaster** [comment]
Another example - what if I wanted to use a mongodb driver with Nuxt. I had thought it would be possible and I'd simply write logic for when the static site is generated to handle getting stuff.

**Comment by Atinux** [comment]
Hey @cfjedimaster, sorry for the late answer, I will try to answer every confusion/questions below.

> Please forgive the somewhat vague title. I ran into an interesting issue that is directly related to my lack of understanding about some core Nuxt-ness (that's a word, honest), and I'm wondering if the docs could have helped a bit here.

We are working on the documentation to make it as clear as possible (I wish to be fluent in English so I could write down all I have in my head about Nuxt.js).

> Some context. I was looking at the docs for asyncData and it's use of axios. This worked for me, but I wanted to use request-promise instead. I'm more familiar with that library.

Actually, `request-promise` is not "isomorphic", which means it cannot run on browser and node.js, axios can, this is why we strongly recommend to use it (and Vue.js team does too).

> I thought that in it's "server" mode, it was a Node server. And that I could add any old module I wanted to. I also thought that asyncData() was completely server side. One of the things a user on chat said was that asyncData can actually run both on the server and the browser (that wasn't clear at all from the docs).

When running `nuxt`, we create a node.js server and we "server-render" the **first page** you are requesting, then when you navigate, there is no more server-rendering and it acts like a simple single page application.

When you are going to a page with your browser, we execute `asyncData` of the page from the server-side. If you navigate when the page is loaded and you come back to the same page, `asyncData` will be called again, but this time, from the browser.

> So... I guess I'm wrong. When running npm run dev, is it not a Node app like Express. Or maybe it is - but it has to be able to run both in the browser, and the server? I mean I know if I were to generate a SPA from it that request-promise wouldn't work, but I thought if I didn't do that and ran it as a server side app, then I'd be ok.

The point of Nuxt.js is to server render the first request of the user when going to the website. Then, the application load on the client-side and takes over, so no more requests will be send to the server to "server render" the page.

> Another example - what if I wanted to use a mongodb driver with Nuxt. I had thought it would be possible and I'd simply write logic for when the static site is generated to handle getting stuff.

It's a bad pattern, Nuxt.js main scope is UI rendering while abstracting away the client/server distribution, if you want to use a Mongo driver, I strongly recommend to create a REST API with Express and call this API from your Nuxt.js application :)

**Comment by cfjedimaster** [comment]
Thank you for this. I still think I have to "mentally work" on this to grok it, but it is beginning to clear up.
