### ISSUE TITLE
Yarn add fibers explaination

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/nuxtjs.org#1063]
The Nuxt Docs has the package `fibers` listed in the `yarn add` when configuring SASS pre-processing.
What worries me is that there is no explaination why this package is included, or even if it's necessary ?
My previous Nuxt project used Node-sass, so we only had to `yarn add -D sass-loader node-sass`.
Now it's `yarn add -D sass sass-loader fibers`.

**Comment by manniL** [comment]
Hey 👋 
See https://github.com/nuxt/nuxtjs.org/pull/848 for context :)

**Comment by mrleblanc101** [comment]
Alright, thanks. The `fibers` documentation did not help me, but `sass` docs mention this package.
Maybe some explaination of why `fibers` is needed should be added to the Nuxt docs too.
