### ISSUE TITLE
Nested routes custom id

### ISSUE THREAD

**Issue by andysay** [nuxt/nuxtjs.org#110]
hello , i'm try get page by custom id like this ' c0476d0a-7c69-4f87-9b6a-1a931be5fe1a ' 

but nuxt say me page not-found, works only with numbers? how use c0476d0a-7c69-4f87-9b6a-1a931be5fe1a id's .. thanks.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c102">#c102</a>)</em></sub></div>

**Comment by toadkicker** [comment]
I'm using UUID's in my URLS like so:

```
    validate({params}) {
      return params.id.match(/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/)
    },
```
