### ISSUE TITLE
Nuxt SSR with asyncData + axios makes calls on the client-side on route change

### ISSUE THREAD

**Issue by Saunved** [nuxt/nuxtjs.org#1101]
I usually use Nuxt in SPA mode, so I never ran into this issue, but I need to use it in Universal mode now, and I observed asyncData calls showing up in the browser's Network tab.

I am pretty sure I am doing something wrong, but I've spent a long time trying to fix this situation and haven't managed to find any solution or explanation. Please take a look at the [test repository](https://github.com/Saunved/ssr-test) I have created to demonstrate the issue.

You can run the dev server using ```yarn dev``` or start the server using ```yarn build && yarn start```
The issue replicates in both environments.

Open localhost:3000 and keep Developer tools > Network open.
Navigate to the "Users (users.vue)" route using the link at the top. You will see a network call being made on the client-side to fetch data.
Navigate back to the "Posts (index.vue)" route and another network call will be made.

As per my understanding, all calls in asyncData should be made on the server and not in the user's browser. Although this happens on the first load, on subsequent route changes, the calls are being made client-side. Is there something I am doing wrong?

**Things I have tried (unsuccessfully)**
- Wrapping asyncData with process.server (this does not work on route change, no call is made at all)
- Using the fetch() hook: makes no difference
- Using fetch() with fetchOnServer set to true: makes no difference
- Tried using nuxt/http instead of nuxt/axios: makes no difference
- Quadruple-checked the nuxt.config.js to ensure I am running it in SSR mode

Thanks for your help!

**Comment by debs-obrien** [comment]
Exactly what Daniel said. You can read how it works here. I hope that helps with understanding how Nuxt works

https://nuxtjs.org/docs/2.x/concepts/server-side-rendering/

**Comment by Saunved** [comment]
@danielroe @debs-obrien Thank you for shedding light on the situation. The SSR concept doc page clarified a lot of things :smile:
