### ISSUE TITLE
Google Translate fails to translate website

### ISSUE THREAD

**Issue by icarito** [nuxt/nuxtjs.org#112]
Something in Javascript is interferring with Google Translate, because it renders fine initially but then switches to 404 error.

Reproduce:
https://translate.google.com/translate?hl=es&sl=en&tl=es&u=https%3A%2F%2Fnuxtjs.org%2F

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c104">#c104</a>)</em></sub></div>

**Comment by richlloydmiles** [comment]
@pi0 Any thoughts on this?

**Comment by Atinux** [comment]
I looked into it, and sadly, this seems like headache because they use an iframe an some weird links. You can use Chrome and right click -> Translate to XXX.
