### ISSUE TITLE
I want to know what the role of the now.json file is

### ISSUE THREAD

**Issue by se7en-1992** [nuxt/nuxtjs.org#114]
I did not find this file available anywhere in this project

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c105">#c105</a>)</em></sub></div>

**Comment by patrickdaze** [comment]
You're right, there isn't much documentation about this file or how the site is hosted/deployed.

The [now.json](https://github.com/nuxt/nuxtjs.org/blob/master/now.json) file is used by the [Now](https://zeit.co/now) service. It makes it [simple to deploy apps](https://zeit.co/now#get-started).

**Comment by se7en-1992** [comment]
Thank you very much for your answer，
It's really cool when I got to know it.
