### ISSUE TITLE
Avoid confusing middleware and serverMiddleware

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxtjs.org#1143]
(background: [#8626](https://github.com/nuxt/nuxt.js/issues/8626))

If one adds [serverMiddleware](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-servermiddleware) to `middleware/` directory, it will be wrongly picked by nuxt as [middleware](https://nuxtjs.org/docs/2.x/directory-structure/middleware/) which adds wrong dependencies to bundle or generate errors.

It could be nice if in `serverMiddleware` section we explain about difference and a notice to not use `middleware/` directroy

**Comment by manniL** [comment]
Linked the issue in Pooya's post ☺️
