### ISSUE TITLE
Nuxt generate for electron

### ISSUE THREAD

**Issue by raultrysw** [nuxt/nuxtjs.org#116]
Hi, I have two projects, one is the nuxt project I generated with the cli interface and the other is an electron app.
So I tested de nuxt generate command but the result works for me only under a server, so with electron i am not able to work with the file, so me would like a way in which the result would works without a server.
Is this possible?. Thanks!

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c107">#c107</a>)</em></sub></div>

**Comment by cyberiaa** [comment]
Similar issue here!

**Comment by Atinux** [comment]
Wrong repo
