### ISSUE TITLE
页面用了asyncData方法，在浏览器端刷新页面时，会报错

### ISSUE THREAD

**Issue by husilang** [nuxt/nuxtjs.org#122]
某页面用async asyncData 获取数据，从其他页面跳转至此页面时，没有问题，但是在本页面刷新时，asyncData方法获取的数据变成了undefined。
这个是怎么回事，有办法解决吗？

**Comment by husilang** [comment]
用了express启动服务后，就没有这个困扰了

**Comment by xiaonizi0601** [comment]
我也遇到了相同的问题，动态路由页面刷新会报400错误，请问你说的使用“快速启动服务”具体是怎么操作呢？

**Comment by xiaonizi0601** [comment]
我用express启动服务，刷新还是会报错，可以把你的代码贴上来看看吗？

**Comment by yehongrun** [comment]
我也有这样的问题，但报错不是说 asyncData 这个方法问题，而是直接报NuxtServerError

**Comment by grace618** [comment]
我差点以为这是我提的问题，我也碰到这个问题了，请问具体怎么解决的哇，我的不报错

**Comment by bigeyesbro** [comment]
请问解决了问题了吗， 我也遇到了相同的问题

**Comment by ursuchcute** [comment]
请问解决了问题了吗，路由跳转正常，页面刷新后端接受不到参数
