### ISSUE TITLE
Got 500 error, when my internet gone in middle of loading next page

### ISSUE THREAD

**Issue by monishnarwani** [nuxt/nuxtjs.org#123]
![screenshot from 2018-03-20 23-47-51](https://user-images.githubusercontent.com/25245587/37675730-020cbd7c-2c9c-11e8-9988-0bf8837bc934.png)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c112">#c112</a>)</em></sub></div>

**Comment by Atinux** [comment]
Fixed
