### ISSUE TITLE
No eslint configuration found in a linked module

### ISSUE THREAD

**Issue by raultrysw** [nuxt/nuxtjs.org#124]
I have a linked module in my computer and a nuxt project, and when I make require of that module I get the 'No eslint configuration found'
How can I fix that situation? :(
Thanks in advance

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c113">#c113</a>)</em></sub></div>

**Comment by jscottsf** [comment]
I ran across this since I'm experiencing the same issue:

https://stackoverflow.com/questions/48410203/webpack-gives-eslint-errors-while-using-npm-link

Also commented about it here:

https://github.com/nuxt/nuxt.js/issues/947
