### ISSUE TITLE
Add warning about global vuex state with SSR

### ISSUE THREAD

**Issue by robyedlin** [nuxt/nuxtjs.org#125]
If this is not implemented correctly, it can cause major privacy/security issues:

https://nuxtjs.org/guide/vuex-store#modules-mode

> If you want this option, export the state as a function, and the mutations and actions as objects in store/index.js instead of a store instance:

I propose adding a warning in that section. Something like: Assigning state as an object without returning a function will make the state global to everyone if using SSR.

I'd be happy to open a PR if the core team agrees.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c114">#c114</a>)</em></sub></div>

**Comment by Atinux** [comment]
Hi @robyedlin 

Actually, we added a security check directly inside Nuxt.js directly to avoid this security issue: https://github.com/nuxt/nuxt.js/blob/dev/lib/app/store.js#L60

So it's not possible to export an object anymore :)

**Comment by robyedlin** [comment]
Hi @Atinux, can you check this real quick and let me know if you think this is an issue worthy of the documentation.

Great job at Vue Amsterdam, btw! It was a great event. :)

https://github.com/nuxt/nuxt.js/issues/1674#issuecomment-376273314
