### ISSUE TITLE
nuxtServerInit accessing server request 

### ISSUE THREAD

**Issue by linqFR** [nuxt/nuxtjs.org#1252]
Nuxt documentation [(HERE)](https://nuxtjs.org/docs/2.x/directory-structure/store#the-nuxtserverinit-action) gives an example where we can access request in **nuxtServerInit**.
```
actions: {
  nuxtServerInit ({ commit }, { req }) {
    if (req.session.user) {
      commit('user', req.session.user)
    }
  }
}
```
but with params in _nuxt.config.js_
```
target: 'static',
ssr:true,
```
and default mode (so **universal** i suppose).

BUT I can only find _req_ and _res_ in _ssrContext_!!

So, is the example not supposed to be the following instead?

```
actions: {
  nuxtServerInit ({ commit }, {ssrContext:{ req }}) {
    if (req.session.user) {
      commit('user', req.session.user)
    }
  }
}
```

**Comment by linqFR** [comment]
@danielroe so it is not related to mode = 'universal' as doc states?

**Comment by danielroe** [comment]
@linqFR The docs are correct - with a universal target that action is called, and receives the context. It just happens that with static target, req is not on the context.

**Comment by linqFR** [comment]
But in ssrContext, which is not documented?

That's just fine with me ! just that documentation is not very obvious and crystal clear about **universal** mode.
Is it just : `mode ="universal"` or a mix of 
```
mode="universal"
ssr="something"
target="another thing"
```
?

i want a static site, rendered once at first access to website (but with custom config related to user's role and language and to subdomain) and then only data is dynamic (routes, layout, page, plugins... everything else is static!)

**Comment by linqFR** [comment]
> @linqFR The docs are correct - with a universal mode that action is called, and receives the context. It just happens that with static target, req is not on the context.

I am not sure it is about the `target='static'`
It seems more to be:

#### nuxtServerInit is triggers if nuxt config has  `mode = "universal"` (default value)
| if | in `nuxtServerInit( storeCtx, nuxtCtx )`, we have: |
| :-: | :-- |
| `ssr = true` | request = `nuxtCtx.ssrContext.req` / response = `nuxtCtx.ssrContext.res` |
| `ssr = false` | request = `nuxtCtx.req` / response = `nuxtCtx.res` |

**Comment by linqFR** [comment]
@danielroe * well after reading nuxt code I am even not sure this is it !

**Comment by linqFR** [comment]
what happens with following ?
```
target = static
ssr = true
```

**Comment by danielroe** [comment]
What I said above.

**Comment by linqFR** [comment]
sorry i m just trying to figure out what params do what and the usage of all that !
> what happens with following ?
> 
> ```
> target = static
> ssr = true
> ```

what is the flow with such params ? 
- during build (before webpack/after webpack)
- what kind of server will run and what it can do or cannot do


and the cherish on top : what if some modules are added : like PWA or nuxt/content... 

I have started to map things, but i d like to add usage / purpose of config with pure functional point of view !

 

![Image1](https://user-images.githubusercontent.com/18004866/107852952-ca283a00-6e13-11eb-9e74-8504273a0827.png)
