### ISSUE TITLE
Navigation is broken

### ISSUE THREAD

**Issue by nimonian** [nuxt/nuxtjs.org#1272]
When I click a link on nuxtjs.org the url changes but navigation doesn't occur.

I checked the log and this is the err:

```
54033e6.js:2 POST https://plausible.io/api/event net::ERR_BLOCKED_BY_CLIENT
r @ 54033e6.js:2
t @ 54033e6.js:2
n @ 54033e6.js:2
t @ 54033e6.js:2
history.pushState @ 54033e6.js:2
kt @ b7f3eee.js:2
```

Also worth mentioning that the tabs to change language don't seem to work right now:

![image](https://user-images.githubusercontent.com/12779491/108223484-c8bb8200-7131-11eb-92b5-fb89613a8ba3.png)

Bug occurs in chrome and firefox

**Comment by mbraint** [comment]
> Could you hard-refresh please?

I've tried. it didn't help

<img width="1437" alt="Screenshot 2021-02-17 at 22 30 15" src="https://user-images.githubusercontent.com/16642887/108257594-0f2fd180-7170-11eb-97ba-34f14e108db5.png">

**Comment by emaia** [comment]
The navigation works if I disable adblock extension.

**Comment by nimonian** [comment]
Duplicate of ##1278
