### ISSUE TITLE
[NuxtJS Docs] The view is not updated after clicking on a link placed on the left sidebar.

### ISSUE THREAD

**Issue by devictoribero** [nuxt/nuxtjs.org#1277]
As the title indicates, it was my first visiting Nuxtjs (so I had no files cached) and when navigating through the docs, I've seen that If I click on a link that it's on the left sidebar (navigated across different pages) the UI is not updated even though the URL changes. If I refresh, since the URL was updated, the content is shown properly after loading the page.

**FYI: An error is NOT thrown on the console.**

On the other hand, In incognito mode, looks like it does work correctly.

_I'm using chrome Version 88.0.4324.150 (Official Build) (x86_64)_

Look at the video 👇
https://user-images.githubusercontent.com/16169890/108391110-99a71e00-71ce-11eb-8c20-1bdd2b786d6b.mov

**Comment by debs-obrien** [comment]
Thanks @devictoribero we will make sure to test this out. Also if you could keep an eye on it for us and report back in a few days if it is the same behaviour that would also be great. thanks

**Comment by devictoribero** [comment]
Since it was working using the incognito mode, I thought that could be an extension-related issue.

For me, the issue is caused by the ad-block https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom

I've paused it for the nuxtjs docs, and looks like it behaves as it should after doing that @debs-obrien .

**Comment by debs-obrien** [comment]
ok great to know. Thanks @devictoribero 

@Atinux what are your thoughts on this and how we can make Nuxt site work with these types of extensions so people can block adds but still see site?

**Comment by danielroe** [comment]
Fixed in #1281.
