### ISSUE TITLE
Navigating docs not working with (ad/u)block enabled

### ISSUE THREAD

**Issue by YasiOnFire** [nuxt/nuxtjs.org#1278]
## Steps to reproduce:
- install uBlock in firefox/chrome or install Brave browser
- go to https://nuxtjs.org/docs/2.x/get-started/installation
- try to navigate anywhere or change to dark mode

## What should happen:
- URL is changed and the view changes

## What happens:
- URL is changed but nothing else happens

## Disabling uBlock, or buildin Brave blocking fixes the issue.

I think it's caused by plausable.io event being blocked, and thus the routing is not executed properly.

**Comment by meinenieuwland** [comment]
![image](https://user-images.githubusercontent.com/3862658/108508891-ccc7db00-72bc-11eb-8202-5867929456f5.png)
Seeing a "Maximum call size exceeded" error. Maybe some recursive function not being able to finish due to the adblockers?

**Comment by meinenieuwland** [comment]
I checked out the repository locally and your problem with "Maximum call size exceeded" is caused by [`plugins/adblock.client.js`](https://github.com/nuxt/nuxtjs.org/blob/master/plugins/adblock.client.js)

**Comment by febrihidayan** [comment]
@meinenieuwland You are right, I also had the same problem. But on turning off ad blocking it really worked

**Comment by andynunes** [comment]
I also found that I had to disable filtering for this domain within the "AdGuard AdBlocker" Chrome extension in order to navigate the docs.

**Comment by JeffreyDotDev** [comment]
Fixed it in https://github.com/nuxt/nuxtjs.org/pull/1281
