### ISSUE TITLE
edge docs

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxtjs.org#1290]
There are features that land to nuxt's dev branch and get some time until released. In the meantime, these features are available as nighly-builds by using `nuxt-edge` npm package. Idea is that, instead of pending PRs like #1288, we may push them to corresponding dev branch in nuxtjs.org and publish on https://dev.nuxtjs.org Only point is probably that we might need to show a specific banner for subdomain that this docs are for nuxt edge (and maybe then also a page explaining more about nuxt-edge)

**Comment by manniL** [comment]
Great idea!

In addition we could generally inform people about `nuxt-edge`. Possibly a blog post?

**Comment by pi0** [comment]
> In addition we could generally inform people about nuxt-edge. Possibly a blog post?

A status page in docs would probably better since it might be updated (as well ass adding refs to nuxt3 in upcoming months 😁)

**Comment by pi0** [comment]
Closing in favor of #1434
