### ISSUE TITLE
[Bug] /cookbook/components: "Edit on github" returns 404

### ISSUE THREAD

**Issue by Toliak** [nuxt/nuxtjs.org#1299]
**Description**

Link [https://typescript.nuxtjs.org/cookbook/components/](https://typescript.nuxtjs.org/cookbook/components/) appeared in console, after I created a project.

On the website page I saw empty code block and I attempted to see, why did that happen
![image](https://user-images.githubusercontent.com/25643405/109712285-e7e5f500-7bb0-11eb-9000-f19fbcca816b.png)

I clicked "Edit on github" button and got redirected to [https://github.com/nuxt/typescript/edit/main/docs/content/en/cookbook/components.md](https://github.com/nuxt/typescript/edit/main/docs/content/en/cookbook/components.md). However, that page does not exists.

**Comment by kevinmarrec** [comment]
@Atinux It seems to be an issue with `@nuxt/content` with some trailing `/`.

Navigating from docs Home to Components page juste work, but refreshing make it buggy (and we can see it doesn't work only when there's trailing `/`)
