### ISSUE TITLE
Vuex store behaviour when push back button in the browser

### ISSUE THREAD

**Issue by germanp** [nuxt/nuxtjs.org#13]
I've found that when you go back (browser back button) you lost the variables stored in vuex store. This happens because the code that initialized the vuex store (from the backend) gets executed again so the store is restarted. The normal behaviour appears to be that the store remains the same when you go back, like how it works on simple html inputs. So the question is, is there any configuration to preserve the store after going back or it is a bug?

Regards

**Comment by Atinux** [comment]
Hi @germanp 

Can you show a gif of the behaviour you're experiencing?

On Google Chrome, I'm navigating trough https://nuxtjs.org and the back button works perfectly without reloading the page and without emptying the vuex store.

**Comment by germanp** [comment]
Sorry, I forgot to mention that it is after doing a post without ajax and reloading all the page. In summary, you have a form with filled fields and submit them without ajax (doing a full reload and hiting the backend) and then you go back.

I can elaborate an example if it is not clear enough. Thanks

**Comment by Atinux** [comment]
Ok but this is normal since your form reload the page so the history is compromised. You should use Ajax to submit your form @germanp
