### ISSUE TITLE
[edge] css file´s path builded wrong

### ISSUE THREAD

**Issue by juppdes** [nuxt/nuxtjs.org#131]
### Version

[2.0.0-25399171.6985927](https://github.com/nuxt/nuxtjs.org/releases/tag/2.0.0-25399171.6985927)

### Reproduction link

[https://jsfiddle.net/Jupp/adnsv7ef/3/](https://jsfiddle.net/Jupp/adnsv7ef/3/)

### Steps to reproduce

The background file set in the css is searched at 'http://localhost:3333/static/any.jpg', when it should be searched at 'http://localhost:3333/_nuxt/img/any.jpg'

### What is expected ?

That point correctly to the files set in css classes.

### What is actually happening?

I think they are looking for the wrong place.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c118">#c118</a>)</em></sub></div>

**Comment by manniL** [comment]
Wrong repo :see_no_evil: 
Happend to me as well :sweat_smile:

**Comment by juppdes** [comment]
@manniL wrong repo? Sorry.. i didn't understand..

**Comment by manniL** [comment]
@juppdes You've sent the bug report to the "nuxtjs.org" repo (the website of the Nuxt.js project). I think you wanted to submit a report for `nuxt.js` itself. Or am I wrong? :thinking:

**Comment by juppdes** [comment]
Now you got me. should have posted somewhere else?

**Comment by manniL** [comment]
Just like you did (via [CMTY](https://nuxtjs.cmty.io/)) but this time, choose the `nuxt/nuxt.js` repo :relaxed:

**Comment by Atinux** [comment]
We will work on the UI to avoid this issue in the future :)
