### ISSUE TITLE
Open Graph Facebook validator

### ISSUE THREAD

**Issue by geminixandroid** [nuxt/nuxtjs.org#1325]
Facebook open graph validator can't correctly recognize meta tags,  due to 
`data-n-head="ssr" data-hid="og:site_name"`
All open grap tags shows in **untreated tags**

Example: [validate nuxt.org](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fnuxtjs.org%2F)

**Comment by manniL** [comment]
Hey 👋 

This looks fine through the link you posted

![grafik](https://user-images.githubusercontent.com/640208/110909955-fd75c000-8310-11eb-9656-f6d327570bf6.png)

The "extra attributes" shouldn't hinder any crawler to understand the meta tag AFAIK.

**Comment by geminixandroid** [comment]
> Hey 👋
> 
> This looks fine through the link you posted
> 
> ![grafik](https://user-images.githubusercontent.com/640208/110909955-fd75c000-8310-11eb-9656-f6d327570bf6.png)
> 
> The "extra attributes" shouldn't hinder any crawler to understand the meta tag AFAIK.

but it shows
`Based on the raw tags, we constructed the following Open Graph properties`
tags are invalid, but Facebook can recognize it
