### ISSUE TITLE
Add date when publish new release note

### ISSUE THREAD

**Issue by Schum123** [nuxt/nuxtjs.org#133]
### What problem does this feature solve?

Better to see release date.

Not sure if i put this in the right place?

### What does the proposed changes look like?

For example, 25 April 2018 - v1.4.0

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c120">#c120</a>)</em></sub></div>

**Comment by manniL** [comment]
You can see the dates on the [release overview](https://github.com/nuxt/nuxt.js/releases) :relaxed:
