### ISSUE TITLE
[edge] Analyzing build only shows "stat" screen and behaves weird

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxtjs.org#134]
### Version

[2.0.0-25414361.b4a4a55](https://github.com/nuxt/nuxtjs.org/releases/tag/2.0.0-25414361.b4a4a55)

### Reproduction link

[https://github.com/manniL/nuxt-edge-analyze-issue](https://github.com/manniL/nuxt-edge-analyze-issue)

### Steps to reproduce

1. Clone the repo
2. Install modules (npm i)
3. Run an analyze build (npm run build -- -a)
4. See that app.css is included and only that stat view is available

### What is expected?

All overviews should be available.

### What is actually happening?

The app.css is included in the build overview. Only the `stats` page is available. Neither the `parsed` nor the `gzipped` page is accessible.

### Additional comments?

If I remove the `markdown-it` import, everything behaves normally. However, I can't find out why that import is influencing the build step. Could there be a silent error?

The build itself succeeds every time, even when I'm doing more complex things (preprocessing, webpack plugins, extracting css, ...). However, the analytics page always shows the CSS file (even if I minify/extract it through purgeCss and build settings) and only the `stats` page.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c123">#c123</a>)</em></sub></div>

**Comment by blowsie** [comment]
For me no stats page is gerenated at all
```
 /*
   ** Build configuration
   */
  build: {
    /*
     ** You can extend webpack config here
     */
    analyze: true,
    extend(config, ctx) {
      // Run ESLint on save
      if (ctx.isDev && ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  }
```

```
√ Builder initialized                                                 10:50:28
√ Nuxt files generated                                                10:50:29
i Compiling Client                                         webpackbar 10:50:30
i Compiling Server                                         webpackbar 10:50:30
√ Server: Compiled successfully in 9.20s                   webpackbar 10:50:39
√ Client: Compiled successfully in 14.09s                  webpackbar 10:50:44
i Waiting for file changes                                            10:50:44

 WARN  Notice: Please do not deploy bundles built with analyze mode, it's only for analyzing purpose.
```

**Comment by manniL** [comment]
Wrong repo 🤷‍♂️
