### ISSUE TITLE
[edge] css file´s path builded wrong 

### ISSUE THREAD

**Issue by juppdes** [nuxt/nuxtjs.org#135]
### Version

[edge](https://github.com/nuxt/nuxtjs.org/releases/tag/edge)

### Reproduction link

[https://jsfiddle.net/Jupp/adnsv7ef/3/](https://jsfiddle.net/Jupp/adnsv7ef/3/)

### Steps to reproduce

The background file set in the css is searched at 'http://localhost:3333/static/any.jpg', when it should be searched at 'http://localhost:3333/_nuxt/img/any.jpg'

### What is expected ?

That point correctly to the files set in css classes.

### What is actually happening?

I think they are looking for the wrong place.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c124">#c124</a>)</em></sub></div>

**Comment by Atinux** [comment]
Wrong repo
