### ISSUE TITLE
Please provide details about the CSP.

### ISSUE THREAD

**Issue by small-sunshines** [nuxt/nuxtjs.org#147]
### What problem does this feature solve?

Currently, Nuxt.js document describes how to configure CSP, but there is no detailed setup method. I do not even know much about the existence of this feature.

### What does the proposed changes look like?

Please tell me how to set up CSP in detail.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c140">#c140</a>)</em></sub></div>

**Comment by small-sunshines** [comment]
![image](https://user-images.githubusercontent.com/11470513/44025512-59e04742-9f2b-11e8-9e50-d5326e586088.png)

**Comment by small-sunshines** [comment]
![image](https://user-images.githubusercontent.com/11470513/44025555-6e02bba6-9f2b-11e8-9720-6e945402adf5.png)

**Comment by Atinux** [comment]
Any pull request to https://github.com/nuxt/docs is more than welcome :)
