### ISSUE TITLE
Why is the Chinese translation document not displayed on the official website?

### ISSUE THREAD

**Issue by cabbage9** [nuxt/nuxtjs.org#1488]
I cloned the project and found that there was a complete Chinese translation, but when I switched zh on the official website, it was still in English. This doesn't happen when I switch to Japanese.
I wanted to try to solve this problem but I didn't know how the official website was constructed. So if any member saw this issue, please help solve the matching problem. 
Thank you very much！

**Comment by clemcode** [comment]
Hi, we're currently handling a content migration to a more robust system which should be up very soon. 

Thank you for the issue, we'll make sure all translations are available on the correct subdomains.
