### ISSUE TITLE
Debbie is no longer head of learning :(

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxtjs.org#1490]
I believe she's an ambassador now (double check)
https://nuxtjs.org/team

**Comment by sidizawi** [comment]
Hi, I worked on it, and I created a [PR](https://github.com/nuxt/nuxtjs.org/pull/1519)

**Comment by danielroe** [comment]
Thanks for spotting! Now updated [in new site](https://nuxtjs.org/teams).
