### ISSUE TITLE
[Preview] Missing Sponsor

### ISSUE THREAD

**Issue by beliolfa** [nuxt/nuxtjs.org#1533]
64 Robots logo is missing on the partners' carousel.

It is also missing on the sidebar inside Docs and Examples pages.

I'm assuming it's missing everywhere due to the recent incorporation .

Thanks!

**Comment by clemcode** [comment]
Hi @beliolfa 

Indeed due to the parallel development of the new website, the logo was not integrated, thanks for notifying us.

We'll add it today, sorry for the inconvenience.

**Comment by beliolfa** [comment]
Thank you!
