### ISSUE TITLE
[Docs] "head" should mention that also links can be defined

### ISSUE THREAD

**Issue by rowild** [nuxt/nuxtjs.org#1584]
Here:
https://github.com/nuxt/nuxtjs.org/blob/main/content/en/guides/components-glossary/pages-head.md

the "head" option is discussed. Being new to Nuxt.js, I would believe that this is it. But from what I see in projects and in Debbie's videos, it also allows to define links. This should be discussed or at least mentioned somehow (with a link to a place where "links" are discussed in more detail). And, of course, this would be true, if there are any other options that can be defined in "head".

I found this docu, because I was looking for a way to implement a google font, which has the attribute "crossorigin". So far I haven't found a solution in the documentation that is dedicated to that problem. (Is there any?)

As a sidenote: 
Shouldn't it read "Nuxt.js lets you ..." ("lets" instead of "let")?

**Comment by danimajo** [comment]
checked the ticket, link is now a 404, seems like the guides are gone

https://github.com/nuxt/nuxtjs.org/tree/main/content/en

Is this issue still relevant?

**Comment by rowild** [comment]
No, I guess this issue can be closed. Thanks you for your feedback!
