### ISSUE TITLE
Visit URL is not latest static infomation

### ISSUE THREAD

**Issue by ausir0726** [nuxt/nuxtjs.org#17]
I found this link
https://nuxtjs.org/guide/release-notes/

if you just visit this link , content show latest version is 0.10.5
but if you navigation to other page and back ( with js append content )
it's latest content ( v0.10.6 )

strange....  Don't know have other pages like this ....

**Comment by ausir0726** [comment]
I found this , because I copy the release note to my friend .
but he told me , he only see 0.10.5 release ....

**Comment by alexchopin** [comment]
Thanks @ausir0726  I'll take a look on it 👍

**Comment by alexchopin** [comment]
fixed
