### ISSUE TITLE
Nuxt Contribution Pages... blank pages and broken links

### ISSUE THREAD

**Issue by joshwcorbett** [nuxt/nuxtjs.org#1701]
- [ ] https://nuxtjs.org/guide/contribution-guide/ is completely blank
- [ ] [Link](https://github.com/nuxt/nuxtjs.org/blob/main/content/en/_archives/guide/contribution-guide.md) in website footer for contributing leads to missing Github ReadME

**Comment by bitsnaps** [comment]
As well as many other links (e.g. [configuration-target](https://go.nuxtjs.dev/config-target)...)
