### ISSUE TITLE
All links from a Google search are broken (404)

### ISSUE THREAD

**Issue by ThibaultVlacich** [nuxt/nuxtjs.org#1704]
With the launch of the new website, looks like you changed the URL pattern of the documentation, meaning that when searching something on Google, all results from the Nuxt doc are now 404 :/

Example of a search: https://www.google.com/search?q=nuxt+asyncdata

Top results are 404

**Comment by ctwhome** [comment]
another example: https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-build/

**Comment by jameswragg** [comment]
The entire Internals & Components Glossary sections are currently broken/missing and some of the Configuration Glossary is missing on the new docs site.

**Configuration Glossary**
"The server Property" down is all broken/missing, e.g.
https://nuxtjs.org/docs/configuration-glossary/configuration-server
https://nuxtjs.org/docs/configuration-glossary/configuration-servermiddleware
https://nuxtjs.org/docs/configuration-glossary/configuration-srcdir

**Internals Glossary**
https://nuxtjs.org/docs/internals-glossary/context
https://nuxtjs.org/docs/internals-glossary/$nuxt
https://nuxtjs.org/docs/internals-glossary/internals
etc.

**Components Glossary**
https://nuxtjs.org/docs/components-glossary/fetch
https://nuxtjs.org/docs/components-glossary/head
https://nuxtjs.org/docs/components-glossary/key
etc.

I'm unimpressed with the QA done (or not done) on the new site.

**Comment by athulanilthomas** [comment]
@jameswragg These links are working for me,

**Comment by ctwhome** [comment]
These things happen all the time, I think that after rushing the team to give updates, the minimum for us is to bring constructive feedback. Also, the links starting to look good again

**Comment by jameswragg** [comment]
@athulanilthomas You're night, I hard-refreshed & its working now.

I still had a tab open on the docs (without refreshing) so was able to record the behaviour:
![Screen Recording 2021-09-16 at 11 27 23 am](https://user-images.githubusercontent.com/204175/133597039-e9177b5f-a64d-4849-8b35-147ab3848060.gif)

Guess it was an issue with deploy?

**Comment by Uninen** [comment]
Possibly related, some of the shortened URLs in generated `nuxt.config.js` are returning a 404. For example: https://go.nuxtjs.dev/config-build -> https://nuxtjs.org/guides/configuration-glossary/configuration-build -> 404

**Comment by tomatebg** [comment]
The new documentation is much smaller than the previous one, it was difficult to recommend content for some students after the update. It would be respectful of the devs and project continuity to keep previous documentations up and running.

**Comment by Atinux** [comment]
Thanks for the update, most of the links should be fixed thanks to #1756 

What do you mean by much smaller than the previous one @tomatebg ?

PS, the old documentation is available on https://old.nuxtjs.org for the moment
