### ISSUE TITLE
Nuxt deployment on DigitalOcean app platform documentation suggestion

### ISSUE THREAD

**Issue by spirico** [nuxt/nuxtjs.org#1731]
Greetings!

First of all, thanks a lot to everyone who works on such a great tool and documentation for that!

In the article about the Nuxt to DO deployment, the main points are described well (https://nuxtjs.org/integrations/deployments/digital-ocean/).

However, I faced the issue of the universal app deployment during the "health check" stage (and, during issue research, I saw that many other people faced the same issue too). It is related to the host/port settings of the app. The default for that is localhost:3000. But to deploy the app correctly, it is needed to configure the host/port in Nuxt app config or (which is works for me) in the DO app settings.
As for me, it is simpler to set at the DO app settings "**run command**" as this:
```npm start -- --hostname 0.0.0.0 --port 8080```
The other default things work perfectly.

So, probably, it would be worth including the 5th point to the **Setup** section about that.

I found the solution in this article:
https://dev.to/tillsanders/deploy-nuxt-js-on-digitalocean-app-platform-in-5-minutes-or-less-2dij

Best regards

**Comment by pi0** [comment]
As a quick fix (without nitro), it would be a nice to at least directly linking the article in a banner on DO page.

Also /cc @Dawntraoz I know she made two nice articles about app platform. (https://dev.to/dawntraoz/deploy-potatizer-to-digitalocean-1681)
