### ISSUE TITLE
EditOnGithub link is wrong

### ISSUE THREAD

**Issue by HZooly** [nuxt/nuxtjs.org#1743]
Every links calculated at https://github.com/nuxt/nuxtjs.org/blob/main/components/molecules/EditOnGithub.vue#L58 are wrong and lead to a 404 page.

**Comment by rajmondburgaj** [comment]
@HZooly does this line of code generate nuxt.config.js links or is it related to sth else ? I am asking because I wanted to create a bug ticket for nuxt.config.js wrong links but wanted to make sure to not create duplicates.

**Comment by HZooly** [comment]
@rajmondburgaj maybe it's related for every links in the documentation, but I've noted that only on `EditOnGithub` component.
