### ISSUE TITLE
Homepage (top page) is not for ready translate.

### ISSUE THREAD

**Issue by nayuta** [nuxt/nuxtjs.org#178]
### What problem does this feature solve?

Homepage (top page) contents are written in the source code directory. Therefore, we cannot translate it for each language.

### What does the proposed changes look like?

Move contents to language resource files, lang.json, and content files, *.md. I'll send pull request after submit it.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c158">#c158</a>)</em></sub></div>

**Comment by nayuta** [comment]
I'd send pull request below:
- Move resources to language files
  - [/nuxt/nuxtjs.org/pull/179]
  - [/nuxt/docs/pull/1272]
- Move contents to documens, `/(lang)/homepage/*.md`
  - [/nuxt/nuxtjs.org/pull/180]
  - [/nuxt/docs/pull/1273]

**Comment by nayuta** [comment]
Implement notes:
I'd move the homepage contents to `/(lang)/homepage/*.md`, not all to `/(lang)/lang.json`. Because:
1. `lang.json` format is not suitable for some contents. Paragraphs are long, and some contents lose their design.
2. Docs api server rendered markdown files at the server side. `lang.json` is not rendered.

I'd add new api, `/homepage/(lang)` to fetch homepage contents, instead using `/(lang)/homepage/*.md`.
Because:
1. The current homepage consists of 11 pieces of contents. If we use the current document api, each client requests 11 api to render at once.
2. I think it needs the fallback function to render every language with no document added.

"New api" is optional. We can use the current document api at rendering homepage. It is more stable. I can rewrite pull requests to do it.

Please send me feedback to translate the beautiful homepage!

**Comment by Atinux** [comment]
You rock :)
