### ISSUE TITLE
Navbar problems on iPad

### ISSUE THREAD

**Issue by Alex-Sokolov** [nuxt/nuxtjs.org#18]
Open docs site on iPad. Navbar looks very bad

![img_1991](https://cloud.githubusercontent.com/assets/4497128/25315298/e009985c-285b-11e7-9554-0e5a05d9a4c5.PNG)

**Comment by alexchopin** [comment]
Thanks for the reporting, I'll work on it 👍

**Comment by alexchopin** [comment]
Fixed
