### ISSUE TITLE
 problem on https://nuxtjs.org/modules

### ISSUE THREAD

**Issue by samehdoush** [nuxt/nuxtjs.org#1830]
### Steps to reproduce
visit page : 
https://nuxtjs.org/modules

Scroll down
All data will be gone

Browser: Microsoft edge Version  94.0.992.38
Browser: chrome Version 94.0.4606.71
Screen size : 2560 * 1440

![image](https://user-images.githubusercontent.com/48515888/136162892-b59af049-cb13-4ad3-bc51-7b3c43042686.png)

**Comment by rishi-raj-jain** [comment]
@samehdoush Are you sure that's happening now? Feel free to close it in case you find it working.
