### ISSUE TITLE
Typescript Support: Instruction not clear

### ISSUE THREAD

**Issue by ram231** [nuxt/nuxtjs.org#188]
I've read the tutorial on how to setup Typescript support for [nuxtjs](https://nuxtjs.org/guide/typescript). should I rewrite the script tag and change it to typescript?
From JavaScript to TypeScript, I tried to rename `nuxt.config.js` to `nuxt.config.ts`

it gives me an error about nuxt.config.js not located.

I believe that the documentation has not been updated and I'll be waiting for it patiently. for the meantime, I'll try the nuxt-typescript template from the [nuxt-community](https://github.com/nuxt-community/typescript-template).

**Comment by webcoderkz** [comment]
I just renamed nuxt.config.js to nuxt.config.ts and it works. I'm using 2.10 version.
