### ISSUE TITLE
Search returns no results on https://nuxtjs.org/modules

### ISSUE THREAD

**Issue by boulderwebdev** [nuxt/nuxtjs.org#1899]
### Bug
If I search with the query `markdown` on `https://nuxtjs.org/modules?q=markdown` I get empty results. In addition, refreshing also is broken, giving no results. If I use the [same query](https://modules.nuxtjs.org/?q=markdown&orderBy=desc) on the old modules page, I'm given two results.

### Environments used
* Firefox 90.0 (64-bit) on Ubuntu 21.10
* Chromium Version 95 (Official Build) snap (64-bit)

Also, typing into the search bar is very slow. I'm surprised there isn't a debounce feature being used. I can add this as an issue after this bug is fixed.

**Comment by smarroufin** [comment]
This page no longer exists.
