### ISSUE TITLE
Display bug on docs

### ISSUE THREAD

**Issue by sandro-git** [nuxt/nuxtjs.org#1936]
i don't know if you're aware but there is weird link or image in the botton of this page https://nuxtjs.org/fr/docs/configuration-glossary/configuration-dev
<img width="1512" alt="Capture d’écran 2021-11-17 à 17 58 19" src="https://user-images.githubusercontent.com/17152022/142246959-ed49b9e5-cde6-45b1-9748-771fca04218a.png">

**Comment by sandro-git** [comment]
i just check on other pages it's the same.

**Comment by smarroufin** [comment]
Thanks for the report :green_heart:

**Comment by sandro-git** [comment]
You’re welcome I try to solve it too make a pull request but it’s not my skill level I guess 😉👍🏽
