### ISSUE TITLE
Link in Doc die

### ISSUE THREAD

**Issue by chleeab** [nuxt/nuxtjs.org#1941]
When I try to https://nuxtjs.org/docs/directory-structure/store through the navigation bar, it return below

![圖片](https://user-images.githubusercontent.com/88308388/142351525-b88e9827-2032-4ff3-9110-5031e1db5129.png)

But I can access it directly.

**Comment by smarroufin** [comment]
Hi @chleeab thanks for the report.
Can you confirm me that if you refresh your page, it loads properly?
This should be related to #1726

**Comment by chleeab** [comment]
I believe is same issue. Sorry for opening new issue.
It work perfectly now.
