### ISSUE TITLE
[Doc] Algolia search not working in docs

### ISSUE THREAD

**Issue by mauriceoegerli** [nuxt/nuxtjs.org#1967]
When searching for any term, the search results return "No results". This is the case on both nuxtjs.org and v3.nuxtjs.org.
![image](https://user-images.githubusercontent.com/15955392/146382871-9871dbcb-fd7f-4054-8a20-62a609d6fa6d.png)

**Comment by smarroufin** [comment]
Hi @mauriceoegerli, thanks for the report.
We are aware of this and it will hopefully be fixed very soon.

**Comment by smarroufin** [comment]
Related issue: https://github.com/algolia/docsearch-configs/issues/4953
