### ISSUE TITLE
What is the double colon syntax in the markdown pages?

### ISSUE THREAD

**Issue by MrHBS** [nuxt/nuxtjs.org#1968]
What is the double colon syntax used in the pages? Eg ::alert{type="next"}

**Comment by smarroufin** [comment]
Hi @MrHBS 
This is the MDC (MarkDown Component) syntax. An homemade syntax for Docus allowing to declare Vue components in an md file.
Currently I cannot link you any docs or repo since all of this is private, but you will surely be able to check this out in a while!

**Comment by MrHBS** [comment]
@smarroufin I really love this syntax and I want to us it in my upcoming blog. Too bad it is private 🙁
