### ISSUE TITLE
[Translation] Translation to Portuguese (Brazil)

### ISSUE THREAD

**Issue by felipesuri** [nuxt/nuxtjs.org#1975]
Hi everyone! 

Today I've started hard work to translate the website to Portuguese, helping Nuxt to be better understood by the Brazilian and Portuguese community.

@smarroufin I feel dedicated and want to actively contribute to Portuguese translations.

Obs.: This is my first PR on open-source projects.

**Comment by smarroufin** [comment]
Hey @felipesuri !
Glad to hear that :blush:
Feel free to make PRs and current portuguese contibutors will be able to certify your good work! :green_heart: 
PS: I don't know if this was supposed to be a PR but it is an issue

**Comment by felipesuri** [comment]
@smarroufin This is an issue, I will create a PR when finish.

**Comment by nazarepiedady** [comment]
Before you starting translating the documentation you should open a issue to ask there are some more people translating the documentation to coordinate the tasks thus avoiding conflicts in process. You worked on the folder I was working and I will need send all my work to trash.

I and [Brendon Henrique](https://www.linkedin.com/in/brendon-henrique-s-s-3b5219156/), we divided the tasks and you come in the middle without warning making us work in vain.

**Comment by smarroufin** [comment]
Hi @nazarepiedady

> Before you starting translating the documentation you should open a issue to see if there are some more people which are translating the documentation to coordinate the tasks thus avoiding conflicts in process. You worked on the folder I was working and I will need send all my work to trash.

I'm not sure to understand your comment clearly, but you seem to complain about him not "warning", but he just did by this issue and you apparently read it, so I think we are all good here.

I might have missed your issue warning about your current work or your draft PR, but there is none. So how could he knows about it?

> I and Brendon Henrique, we divided the tasks and you came in the middle without warning making us work in vain.

Please feel free to make it public so more contributors like @felipesuri can help.

Anyways, it happens in OSS, we resolve conflicts and move on.

I would strongly recommand you guys to work folder by folder, or even page by page, so PRs are quickly reviewed and merged.
Don't bother about trying to translate the whole website in one PR. Nobody likes to review those massive PRs.

> One more point since there is only English and not English UK or English US, with Portuguese should be the same.

For `content` folder, there is no locale, only languages. So I guess `i18n` folder could do the same. For the most part, those are legacy files from the old website. If you consider pt-pt and pt-br being close enough to only have one file, sure just make a PR of it, I will accept it.

English fallback is still not there, sorry about it. It does not block you guys from translating only one page and leaving the other ones in english :ok_hand:

**Comment by nazarepiedady** [comment]
Hi, @smarroufin, sorry to bother you with this situation.

@BrendonHenrique call for my help when he did the first pull request with first documents translated, after that we combined to divide the efforts where I could that folders (`pt/deployments/`, `pt/docs/03-features` and `pt/docs/4-directory-structure`) where I am working now, and @BrendonHenrique should take the next folders inside `docs` such as `docs/5-configuration-glossary` and `docs/6-internals-glossary`.

I am really happy helping for good for this ambitious project, once again I'm very sorry for this situations and We will find a way to put it in order.

**Comment by smarroufin** [comment]
No worries :ok_hand: as long as every wanting to contribute can do it :slightly_smiling_face: 

Can't wait to see all your work guys! :green_heart:

**Comment by smarroufin** [comment]
I close this issue and let you guys organize yourselves in #1984 :slightly_smiling_face:
