### ISSUE TITLE
Static folder in Nuxt 3

### ISSUE THREAD

**Issue by Agusnez** [nuxt/nuxtjs.org#1986]
Hi! I noticed that on the [oficial documentation](https://nuxtjs.org/docs/directory-structure/static/) it says that `/static` is the default static folder for Nuxt similar to the `/assets` directory for Webpack. (also available in Nuxt, by the way). But since Nuxt uses Vite, the [documentation of Vite](https://vitejs.dev/guide/assets.html#the-public-directory) says that it uses `/public` as the static folder.

I have tested both folders in Nuxt 3 and seems that the Vite documentation is right and the `/static` folder does not work for me.

What could be happening?

**Comment by smarroufin** [comment]
Hi @Agusnez 
I think you got the wrong documentation. For Nuxt v3, you have to refer to https://v3.nuxtjs.org/docs/
And it says to use `/public`: https://v3.nuxtjs.org/docs/directory-structure/public

**Comment by Agusnez** [comment]
@smarroufin You are right. I got it completely wrong 🤦‍♂️. Thanks for clarifying it.
