### ISSUE TITLE
Nuxt build and deploy

### ISSUE THREAD

**Issue by PMLS3** [nuxt/nuxtjs.org#1992]
We are trying to get PWA to work on nuxt3 - repo https://github.com/ctwhome/top-nuxt3

When built locally and running nuxt start, everything is working 100%.

but once build on deployment (google cloud, netlify) the build doesn't create a crucial file: /usr/src/app/.output/server/chunks/client.manifest.mjs

Does anyone know why it will build locally and not in cloud? 

We have a open issue on this https://github.com/ctwhome/top-nuxt3/issues/3

**Comment by smarroufin** [comment]
@danielroe Related to Nuxt 3, to move to nuxt/framework

**Comment by danielroe** [comment]
@PMLS3 Would you create an issue with a reproduction via https://github.com/nuxt/framework/issues/new/choose?
