### ISSUE TITLE
HTTPS redirection

### ISSUE THREAD

**Issue by Xowap** [nuxt/nuxtjs.org#2]
Well, me again.

Looks like links were fixed in #1 but now they lead to a page without a trailing `/`, which triggers a redirection... in HTTP (not "S").

So basically, any link you click brings you to the HTTP website. Kind of sad I think.

**Comment by Atinux** [comment]
This was because of our CloudFare configuration (I forgot to redirect the http://nuxtjs.org/* urls to HTTPS.

Now it's fixed, thank you for spotting it @Xowap 👏

**Comment by Xowap** [comment]
:+1:
