### ISSUE TITLE
there is a "undefined"  text in the body  

### ISSUE THREAD

**Issue by fxh615** [nuxt/nuxtjs.org#20]
there is a undefined  text in the body

**Comment by Atinux** [comment]
Can you provide the link or a screenshot @fxh615 ?

**Comment by fxh615** [comment]
<link data-n-head="true" rel="icon" type="image/x-icon" href="favicon.ico"/>undefined 

just like this all time there is a 'undefined '

**Comment by fxh615** [comment]
<!DOCTYPE html>
<html data-n-head-ssr data-n-head="">
  <head>
    <meta data-n-head="true" charset="utf-8"/><meta data-n-head="true" name="viewport" content="width=device-width, initial-scale=1"/><meta data-n-head="true" hid="description" name="description" content="My custom description"/><title data-n-head="true">Hello World!</title><link data-n-head="true" rel="icon" type="image/x-icon" href="favicon.ico"/>undefined
  </head>
  <body data-n-head="">
    <div id="__nuxt" server-rendered="true"><div class="progress" style="width:0%;height:2px;background-color:#3B8070;opacity:0;" data-v-5c1467c9></div><div class="default"><div class="ads-header" data-v-12c8bc0f><div class="header-top" data-v-12c8bc0f><div class="r" data-v-12c8bc0f><span class="icon-user" data-v-12c8bc0f></span><span class="login-name" data-v-12c8bc0f>Allen Iverson</span></div></div><div class="header-btm" data-v-12c8bc0f><ul data-v-12c8bc0f><li data-v-12c8bc0f><a href="/create" data-v-12c8bc0f><span class="icon icon-create-adv" data-v-12c8bc0f></span><span class="words" data-v-12c8bc0f>创建广告</span></a></li><li data-v-12c8bc0f><div class="el-dropdown" data-v-12c8bc0f><a href="/manager" class="router-link-exact-active nuxt-link-active" data-v-12c8bc0f><span class="icon icon-adv-manage" data-v-12c8bc0f></span><span class="words" data-v-12c8bc0f>广告管理</span></a><span class="el-dropdown-link" data-v-12c8bc0f><i class="el-icon-caret-bottom el-icon--right" data-v-12c8bc0f></i></span><ul class="el-dropdown-menu" style="display:none;" data-v-12c8bc0f><li class="el-dropdown-menu__item" data-v-12c8bc0f><a href="/manager" class="router-link-exact-active nuxt-link-active" data-v-12c8bc0f>广告系列</a></li><li class="el-dropdown-menu__item" data-v-12c8bc0f><a href="/manager/ads-group" data-v-12c8bc0f>
                        广告组
                    </a></li><li class="el-dropdown-menu__item" data-v-12c8bc0f><a href="/manager/ads" data-v-12c8bc0f>
                        广告
                        </a></li><li class="el-dropdown-menu__item" data-v-12c8bc0f><a href="/manager/abTest" data-v-12c8bc0f>
                        ABTest
                        </a></li></ul></div></li><li data-v-12c8bc0f><a href="/statistics" data-v-12c8bc0f><span class="icon icon-statistical-analysis" data-v-12c8bc0f></span><span class="words" data-v-12c8bc0f>统计分析</span></a></li><li data-v-12c8bc0f><a href="/adv-assets" data-v-12c8bc0f><span class="icon icon-adv-assets" data-v-12c8bc0f></span><span class="words" data-v-12c8bc0f>广告资产</span></a></li><li data-v-12c8bc0f><a href="/account" data-v-12c8bc0f><span class="icon icon-platform-account" data-v-12c8bc0f></span><span class="words" data-v-12c8bc0f>平台账户</span></a></li></ul></div></div><div class="container"><div class="content" data-v-1e00aac7><div data-v-bcd44a38 data-v-1e00aac7><div class="el-dialog__wrapper" style="display:none;" data-v-bcd44a38><div class="el-dialog el-dialog--small" style="top:15%;"><div class="el-dialog__header"><span class="el-dialog__title">广告系列</span><div class="el-dialog__headerbtn"><i class="el-dialog__close el-icon el-icon-close"></i></div></div><div class="el-dialog__footer"><div class="dialog-footer" data-v-bcd44a38><div class="btn_common_white btn_common_small " data-v-bcd44a38>取消</div><div class="btn_common_yellow btn_common_small btn-common" data-v-bcd44a38>确定</div></div></div></div></div><div class="el-dialog__wrapper" style="display:none;" data-v-bcd44a38><div class="el-dialog el-dialog--small" style="top:15%;"><div class="el-dialog__header"><span class="el-dialog__title"></span><div class="el-dialog__headerbtn"><i class="el-dialog__close el-icon el-icon-close"></i></div></div><div class="el-dialog__footer"><div data-v-bcd44a38><div class="btn_common_white btn_common_small " data-v-bcd44a38>取消</div><div class="btn_common_yellow btn_common_small btn-common" data-v-bcd44a38>确定</div></div></div></div></div></div><div class="container-wrapper" data-v-c79e1600 data-v-1e00aac7><div class="el-select filter-segment" data-v-c79e1600><div class="el-input el-input--small"><i class="el-input__icon el-icon-caret-top"></i><input type="text" placeholder="细分受众统计" readonly="readonly" autocomplete="off" value="" class="el-input__inner"></div><div class="el-select-dropdown" style="min-width:;display:none;"><div class="el-scrollbar is-empty" style="display:none;"><div class="el-select-dropdown__wrap el-scrollbar__wrap el-scrollbar__wrap--hidden-default"><ul class="el-scrollbar__view el-select-dropdown__list"><li class="el-select-dropdown__item" data-v-c79e1600><span>细分受众统计</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>年龄</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>性别</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>年龄和性别</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>地区</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>展示设备</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>平台</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>平台-版位-设备</span></li></ul></div><div class="el-scrollbar__bar is-horizontal"><div class="el-scrollbar__thumb" style="width:0;transform:translateX(0%);ms-transform:translateX(0%);webkit-transform:translateX(0%);"></div></div><div class="el-scrollbar__bar is-vertical"><div class="el-scrollbar__thumb" style="height:0;transform:translateY(0%);ms-transform:translateY(0%);webkit-transform:translateY(0%);"></div></div></div><p class="el-select-dropdown__empty">无数据</p></div></div><div class="account-wrapper" data-v-c79e1600><div class="warn-wrapper" style="display:none;" data-v-c79e1600><i class="icon-remand warn-txt" data-v-c79e1600></i><span class="warn-txt" data-v-c79e1600>账户余额少于广告预算，为了不影响您的广告正常投放，请到Facebook平台上进行充值。</span></div><div class="account" data-v-c79e1600><div class="item" data-v-c79e1600><i class="icon-account-balance" data-v-c79e1600></i><div class="item-wrapper" data-v-c79e1600><div class="item-detail" data-v-c79e1600>¥ 20.00</div><div class="item-desc" data-v-c79e1600>账户余额</div></div></div><div class="item" data-v-c79e1600><i class="icon-casted" data-v-c79e1600></i><div class="item-wrapper" data-v-c79e1600><div class="item-detail" data-v-c79e1600>¥ 20000000.00</div><div class="item-desc" data-v-c79e1600>已花费</div></div></div><div class="btn_common_yellow btn_common_small btn-recharge" data-v-c79e1600>充值</div></div></div><div class="menu-wrapper" data-v-c79e1600><a href="/manager" class="router-link-exact-active nuxt-link-active" data-v-c79e1600><div class="item active" data-v-c79e1600>广告系列</div></a><a href="/manager/ads-group" data-v-c79e1600><div class="item" data-v-c79e1600>广告组</div></a><a href="/manager/ads" data-v-c79e1600><div class="item" data-v-c79e1600>广告</div></a></div><div class="filter-wrapper" data-v-c79e1600><div class="filter-left" data-v-c79e1600><div class="el-select filter-item0" data-v-c79e1600><div class="el-input el-input--small"><i class="el-input__icon el-icon-caret-top"></i><input type="text" placeholder="广告发布时间" readonly="readonly" autocomplete="off" value="" class="el-input__inner"></div><div class="el-select-dropdown" style="min-width:;display:none;"><div class="el-scrollbar is-empty" style="display:none;"><div class="el-select-dropdown__wrap el-scrollbar__wrap el-scrollbar__wrap--hidden-default"><ul class="el-scrollbar__view el-select-dropdown__list"><li class="el-select-dropdown__item" data-v-c79e1600><span>今天</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>昨天</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>广告发布期间</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>近7天</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>近14天</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>近30天</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>自定义时间</span></li></ul></div><div class="el-scrollbar__bar is-horizontal"><div class="el-scrollbar__thumb" style="width:0;transform:translateX(0%);ms-transform:translateX(0%);webkit-transform:translateX(0%);"></div></div><div class="el-scrollbar__bar is-vertical"><div class="el-scrollbar__thumb" style="height:0;transform:translateY(0%);ms-transform:translateY(0%);webkit-transform:translateY(0%);"></div></div></div><p class="el-select-dropdown__empty">无数据</p></div></div></div><div class="filter-right" data-v-c79e1600><div class="el-select filter-item1" data-v-c79e1600><div class="el-input el-input--small"><i class="el-input__icon el-icon-caret-top"></i><input type="text" placeholder="广告目标" readonly="readonly" autocomplete="off" value="" class="el-input__inner"></div><div class="el-select-dropdown" style="min-width:;display:none;"><div class="el-scrollbar is-empty" style="display:none;"><div class="el-select-dropdown__wrap el-scrollbar__wrap el-scrollbar__wrap--hidden-default"><ul class="el-scrollbar__view el-select-dropdown__list"><li class="el-select-dropdown__item" data-v-c79e1600><span>广告目标</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>访问量</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>品牌知名度</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>主页点赞</span></li></ul></div><div class="el-scrollbar__bar is-horizontal"><div class="el-scrollbar__thumb" style="width:0;transform:translateX(0%);ms-transform:translateX(0%);webkit-transform:translateX(0%);"></div></div><div class="el-scrollbar__bar is-vertical"><div class="el-scrollbar__thumb" style="height:0;transform:translateY(0%);ms-transform:translateY(0%);webkit-transform:translateY(0%);"></div></div></div><p class="el-select-dropdown__empty">无数据</p></div></div><div class="el-select filter-item1" data-v-c79e1600><div class="el-input el-input--small"><i class="el-input__icon el-icon-caret-top"></i><input type="text" placeholder="投放状态" readonly="readonly" autocomplete="off" value="" class="el-input__inner"></div><div class="el-select-dropdown" style="min-width:;display:none;"><div class="el-scrollbar is-empty" style="display:none;"><div class="el-select-dropdown__wrap el-scrollbar__wrap el-scrollbar__wrap--hidden-default"><ul class="el-scrollbar__view el-select-dropdown__list"><li class="el-select-dropdown__item" data-v-c79e1600><span>草稿</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>待审核</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>未通过</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>投放中</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>未投放</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>已排期</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>已暂停</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>已完成</span></li></ul></div><div class="el-scrollbar__bar is-horizontal"><div class="el-scrollbar__thumb" style="width:0;transform:translateX(0%);ms-transform:translateX(0%);webkit-transform:translateX(0%);"></div></div><div class="el-scrollbar__bar is-vertical"><div class="el-scrollbar__thumb" style="height:0;transform:translateY(0%);ms-transform:translateY(0%);webkit-transform:translateY(0%);"></div></div></div><p class="el-select-dropdown__empty">无数据</p></div></div><div class="el-select filter-item3" data-v-c79e1600><div class="el-input el-input--small"><i class="el-input__icon el-icon-caret-top"></i><input type="text" placeholder="计费方式" readonly="readonly" autocomplete="off" value="" class="el-input__inner"></div><div class="el-select-dropdown" style="min-width:;display:none;"><div class="el-scrollbar is-empty" style="display:none;"><div class="el-select-dropdown__wrap el-scrollbar__wrap el-scrollbar__wrap--hidden-default"><ul class="el-scrollbar__view el-select-dropdown__list"><li class="el-select-dropdown__item" data-v-c79e1600><span>展示次数</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>链接点击量</span></li><li class="el-select-dropdown__item" data-v-c79e1600><span>主页赞</span></li></ul></div><div class="el-scrollbar__bar is-horizontal"><div class="el-scrollbar__thumb" style="width:0;transform:translateX(0%);ms-transform:translateX(0%);webkit-transform:translateX(0%);"></div></div><div class="el-scrollbar__bar is-vertical"><div class="el-scrollbar__thumb" style="height:0;transform:translateY(0%);ms-transform:translateY(0%);webkit-transform:translateY(0%);"></div></div></div><p class="el-select-dropdown__empty">无数据</p></div></div><div class="filter-item2 el-input el-input--small" data-v-c79e1600><i class="el-input__icon el-icon-search is-clickable"></i><input type="text" placeholder="请输入搜索内容" autocomplete="off" value="" class="el-input__inner"></div><div class="line" data-v-c79e1600></div><div class="btn_common_white btn_common_small" data-v-c79e1600><i class="icon-export" data-v-c79e1600></i>导出</div></div></div><div class="shadow" data-v-c79e1600></div></div><div class="table-head" data-v-1e00aac7><div class="head-left" data-v-1e00aac7>广告系列</div><div class="head-right" data-v-1e00aac7>成效</div></div><div class="table" data-v-1e00aac7><div class="el-table el-table--fit el-table--enable-row-hover el-table--enable-row-transition" style="width:100%;" data-v-1e00aac7><div class="hidden-columns"><div data-v-1e00aac7></div><div data-v-1e00aac7></div><div data-v-1e00aac7></div><div data-v-1e00aac7></div><div data-v-1e00aac7></div><div data-v-1e00aac7></div><div data-v-1e00aac7></div><div data-v-1e00aac7></div><div data-v-1e00aac7></div><div data-v-1e00aac7></div><div data-v-1e00aac7></div><div data-v-1e00aac7></div><div data-v-1e00aac7></div></div><div class="el-table__header-wrapper"><table cellspacing="0" cellpadding="0" border="0" class="el-table__header" style="width:;"><colgroup></colgroup><thead><tr></tr></thead></table></div><div class="el-table__body-wrapper"><table cellspacing="0" cellpadding="0" border="0" class="el-table__body" style="width:;"><colgroup></colgroup><tbody><tr></tr><tr></tr><tr></tr><tr></tr><tr></tr><tr></tr><tr></tr></tbody></table></div><div class="el-table__column-resize-proxy" style="display:none;"></div></div><div class="sum-wrapper" data-v-1e00aac7></div><div class="pagination el-pagination" data-v-1e00aac7><button type="button" class="btn-prev"><i class="el-icon el-icon-arrow-left"></i></button><ul class="el-pager"><li class="number">1</li><li class="number">2</li><li class="number">3</li><li class="number active">4</li><li class="number">5</li><li class="number">6</li><li class="el-icon more btn-quicknext el-icon-more"></li><li class="number">40</li></ul><button type="button" class="btn-next"><i class="el-icon el-icon-arrow-right"></i></button><span class="el-pagination__sizes"><div class="el-select"><div class="el-input"><i class="el-input__icon el-icon-caret-top"></i><input type="text" placeholder="请选择" readonly="readonly" autocomplete="off" value="10" class="el-input__inner"></div><div class="el-select-dropdown" style="min-width:;display:none;"><div class="el-scrollbar is-empty" style="display:none;"><div class="el-select-dropdown__wrap el-scrollbar__wrap el-scrollbar__wrap--hidden-default"><ul class="el-scrollbar__view el-select-dropdown__list"><li class="el-select-dropdown__item selected"><span>10 条/页</span></li><li class="el-select-dropdown__item"><span>20 条/页</span></li><li class="el-select-dropdown__item"><span>30 条/页</span></li><li class="el-select-dropdown__item"><span>40 条/页</span></li></ul></div><div class="el-scrollbar__bar is-horizontal"><div class="el-scrollbar__thumb" style="width:0;transform:translateX(0%);ms-transform:translateX(0%);webkit-transform:translateX(0%);"></div></div><div class="el-scrollbar__bar is-vertical"><div class="el-scrollbar__thumb" style="height:0;transform:translateY(0%);ms-transform:translateY(0%);webkit-transform:translateY(0%);"></div></div></div><p class="el-select-dropdown__empty">无数据</p></div></div></span><span class="el-pagination__jump">前往<input type="number" min="1" number="true" value="4" class="el-pagination__editor" style="width:30px;">页</span></div></div></div></div><div class="loading-overlay" style="display:none;" data-v-16efe4ac><div class="sk-three-bounce" data-v-16efe4ac><div class="sk-child sk-bounce1" data-v-16efe4ac></div><div class="sk-child sk-bounce2" data-v-16efe4ac></div><div class="sk-child sk-bounce3" data-v-16efe4ac></div></div></div></div></div><script type="text/javascript">window.__NUXT__={"layout":"default","data":[{}],"error":null,"state":{"loading":{"loading":false},"upload":{"showPopoverUploadImg":false,"showPopoverUploadVideo":false},"advAssets":{"advAssetsImagesList":[],"advAssetsVideoList":[],"advAssetssAudienceList":[]},"createAd":{"activeStep":"1","createdStep":"1","adverPlan":"访问量","adverName":"","audienceInfo":{},"audienceTabs":[],"audienceCountTips":{"pcCount":"","mobileCount":"","allCount":""},"adStepList":[{"step":"1","created":false,"click":true,"style":"li-active","title":"广告目标","info":"广告目标","icon":"el-icon-arrow-right"},{"step":"2","created":false,"click":false,"style":"li-default","title":"选择受众","info":"覆盖用户","icon":"el-icon-arrow-right"},{"step":"3","created":false,"click":false,"style":"li-default","title":"预算和排期","info":"","icon":"el-icon-arrow-right"},{"step":"4","created":false,"click":false,"style":"li-default","title":"广告制作","info":"","icon":"el-icon-arrow-right"},{"step":"5","created":false,"click":false,"style":"li-default","title":"发布广告","info":"","icon":"el-icon-arrow-right"}],"budgetSchedule":null,"adCreate":null},"manager":{"managerIndex":0,"showPopover":false,"showTipPopover":false}},"serverRendered":true}</script>
  <script type="text/javascript" src="/_nuxt/manifest.56453d6bd13a59392fe7.js" defer></script><script type="text/javascript" src="/_nuxt/vendor.56453d6bd13a59392fe7.js" defer></script><script type="text/javascript" src="/_nuxt/app.6395ae3336bbb4cc6d11.js" defer></script></body>
</html>

**Comment by Atinux** [comment]
I'm sorry but I don't understand what you mean.

Can you create a reproduction by forking https://glitch.com/edit/#!/nuxt-hello-world?

**Comment by fxh615** [comment]
well i put it on gihub soon

**Comment by fxh615** [comment]
https://github.com/fxh615/ads   there is the demo

**Comment by Atinux** [comment]
![screenshot_2017-04-25_12-02-23](https://cloud.githubusercontent.com/assets/904724/25380021/111f7066-29af-11e7-9b13-e65247acdcc6.png)

It works perfectly on my computer, what is the URL with `undefined`?

**Comment by fxh615** [comment]
its local code ,  have you change something ?  what you version of nuxt ?  this is mine version of nuxt "version": "0.10.6",

**Comment by fxh615** [comment]
can you del the image?

**Comment by Atinux** [comment]
Last version of Nuxt.js

**Comment by fxh615** [comment]
thank you !
