### ISSUE TITLE
deploy nuxtjs universal app into cpanel 

### ISSUE THREAD

**Issue by paypol-software** [nuxt/nuxtjs.org#206]
I am new with nuxtjs and this is my first project of nuxtjs to deploying but I searching a lot from any pages in internet but really couldn't find any good and efficient article about deploying nuxtjs universal app in cpanel please show me right way to deploying nuxtjs into cpanel 
Thanks in advance

**Comment by pietroiusti** [comment]
hi was this resolved?

**Comment by pietroiusti** [comment]
https://github.com/nuxt/nuxt.js/issues/2835

**Comment by jigeshraval** [comment]
Please look at this blog for deployment instructions https://jigeshraval.com/en/blog/vue-js/nuxtjs-universal-application-deployment-in-cpanel
