### ISSUE TITLE
Releases page appears to be broken.

### ISSUE THREAD

**Issue by miclgael** [nuxt/nuxtjs.org#2135]
https://nuxtjs.org/releases/

## Screenshots

**Desktop** 

![CleanShot 2022-09-21 at 11 37 05](https://user-images.githubusercontent.com/4301358/191394800-0dbf9842-3003-44fa-bc6c-745b7e210431.png)

**Mobile (WiFi)**

![IMG_00474D935D42-1](https://user-images.githubusercontent.com/4301358/191400917-6b9fbec6-b7b5-4039-8c88-b20c88a7b4fb.jpeg)

**Mobile (4G)**

![IMG_859C3FC6478B-1](https://user-images.githubusercontent.com/4301358/191401048-9057c07d-3e5d-4e4a-bbaa-5ede3a575610.jpeg)

**Comment by rishi-raj-jain** [comment]
@miclgael Are you sure? The page seems to load fine.
