### ISSUE TITLE
Error 500 on v3.nuxtjs.org

### ISSUE THREAD

**Issue by ozum** [nuxt/nuxtjs.org#2142]
Hi,

I'm getting following page when I go to https://v3.nuxtjs.org. I see the normal page in a split second, but then the following.

Best Regards,

![image](https://user-images.githubusercontent.com/1497060/194843049-0a583490-6be2-49cf-a8ab-70767cc6c4fe.png)

**Comment by danielroe** [comment]
If you force refresh, to clear your cache, does this issue resolve?

**Comment by ozum** [comment]
Yes, it is solved. Thanks,
