### ISSUE TITLE
v3 announcement link is bad.

### ISSUE THREAD

**Issue by taigrr** [nuxt/nuxtjs.org#2163]
![image](https://user-images.githubusercontent.com/8261498/202307848-51be1823-49b4-4670-8125-9a9523877897.png)

The component for the NuxtLink automatically prepends a slash to the link, but the link in the app went from being a relative resource to an absolute one on a new domain.

Clicking on the component sends you to [this page](https://nuxtjs.org/https:/nuxt.com/v3), a 404.

![image](https://user-images.githubusercontent.com/8261498/202308120-c026a2f7-7edb-4cff-9c19-cb3e6d110d98.png)

![image](https://user-images.githubusercontent.com/8261498/202308139-334f2d41-1b08-4b39-9152-8b261eb9578d.png)

credit to @jscottsf for noticing the 404

**Comment by taigrr** [comment]
credit to @jscottsf for noticing the 404

**Comment by taigrr** [comment]
This is closed, but the issue is not solved. Code has been merged but it is not deployed to production.

**Comment by danielroe** [comment]
yes, your fix was good but there was a deployment issue which we'll resolve shortly

**Comment by clemcode** [comment]
We had a deployment issue indeed, it is now deployed, thank you!

https://nuxtjs.org/
