### ISSUE TITLE
I have problem nuxt js on windows 10.

### ISSUE THREAD

**Issue by iamfauzi16** [nuxt/nuxtjs.org#2169]
Hi, there.

i have problem nuxt js on windows 10 i not able  install nuxt js on my system operations. please there can you help me for this issue.

this my issue
![image](https://user-images.githubusercontent.com/53123172/203526132-08d874a8-e78c-4380-a39b-090dd810ec14.png)

**Comment by iamfauzi16** [comment]
![image](https://user-images.githubusercontent.com/53123172/203526532-5116d796-90b3-40b8-aa9d-4dfccfa97f04.png)

**Comment by lextm** [comment]
What version of npm are you using? `npm --version` should show that.

Newer npm (like 8.15.0 I am using) can resolve the needed package `create-nuxt-app` behind the scene. I wonder if you are using an old npm that doesn't do the same.

**Comment by iamfauzi16** [comment]
Hi @lextm ,

i using npm with 8.19.2 version,  maybe there is an error on my device. I will try to do this test on another device

**Comment by lextm** [comment]
@iamfauzi16 Sure. Make sure you follow the latest Nuxt 3 guide, and then deploy to IIS with HttpPlatformHandler.

[The steps](https://halfblood.pro/running-nuxt-3-web-apps-on-iis-with-httpplatformhandler/) are actually simple to follow.

**Comment by iamfauzi16** [comment]
Oke, thank you @lextm .
