### ISSUE TITLE
Community -> Events dead link for Workshop with Alex Lichter

### ISSUE THREAD

**Issue by colinscz** [nuxt/nuxtjs.org#2208]
Hi guys

There is a dead link on the bottom of the homepage within the section "Community --> Events" for the workshop with Alex Lichter pointing here: https://conf.vuejs.de/workshops/nuxt3-the-beginners-workshop/ 

Seems that page is not existing anymore. I didn't find it within the repo so I guess it seems to be managed outside of here, otherwise I would have sent a PR myself to remove/fix it.

Cheers

**Comment by manniL** [comment]
Sad - but yes, indeed it is 404 now 🙈

If you want, you can change the [file here](https://github.com/nuxt/nuxtjs.org/blob/b48e343ed6e00a60835fb6fe64743881ab26295e/content/en/_collections/events/2022.md) and either change the link or remove the event

**Comment by colinscz** [comment]
@manniL sure I will have a look at it. I see there are some event links that point to Vuejs.de in other collections. I double check them and then create a consolidated PR.
