### ISSUE TITLE
User is "trapped" on 404 page

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxtjs.org#231]
When hitting the 404 page, the Nuxt layout isn't applied correctly.

Example URL: https://nuxtjs.org/foobar

![image](https://user-images.githubusercontent.com/640208/65814368-1d7af780-e1e1-11e9-8b0c-1f0f453b0e47.png)

Thus, the user can never access the docs content anymore but menu points below. Navigating to one of them will not re-instantiate the layout though.

![image](https://user-images.githubusercontent.com/640208/65814385-48fde200-e1e1-11e9-95e3-6de65ff48ca2.png)

vs. the page after a full reload
![image](https://user-images.githubusercontent.com/640208/65814436-e22cf880-e1e1-11e9-8159-6c23be3e2f9b.png)

---

Related Nuxt.js issue: https://github.com/nuxt/nuxt.js/issues/2537

**Comment by manniL** [comment]
Still a problem.

**Comment by bdrtsky** [comment]
This happens only after build. In dev everything's ok.
