### ISSUE TITLE
Focusable search input field via shortcut

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxtjs.org#233]
It'd be nice to have a keyboard shortcut, e.g. "CTRL + ." or "/" to focus the site search input field. This is a decent UX improvement I'd say.

## Examples

[ChordAtlas](https://www.chordatlas.com/)

![image](https://user-images.githubusercontent.com/640208/65816275-e9600080-e1f9-11e9-969c-7bd38cb42783.png)

[TailwindCSS](https://tailwindcss.com/)
![image](https://user-images.githubusercontent.com/640208/65815933-d9462200-e1f5-11e9-823e-8335d7575e78.png)

## Tasks

1. Change the search placeholder to indicate that the shortcut is available
2. Implement the shortcut (e.g. with https://github.com/shentao/vue-global-events or https://github.com/ccampbell/mousetrap/)

## Caveats

* Don't use shortcuts that are used for important browser actions and therefore don't allow .preventDefault https://stackoverflow.com/a/40434403/3384501
* I'd advocate *against* `/` as it'll trigger the quick find in Firefox, unless implemented via MouseTrap (as it works on the TailwindCSS page).

**Comment by thiyagu-7** [comment]
I would like to work on this.

**Comment by manniL** [comment]
@thiyagu-7 Go ahead :relaxed:

**Comment by nimitbhargava** [comment]
@manniL 
> I'd advocate against / as it'll trigger the quick find in Firefox, unless implemented via MouseTrap (as it works on the TailwindCSS page).
GitHub has `/` for search shortcut. I tried this on `69.0.1 (64-bit)` Firefox, it seems to work.

Evidence -
![firefox-:](https://user-images.githubusercontent.com/8358694/65890891-4bb72d80-e3c1-11e9-8c4c-899fcc496c83.gif)

What do you think?

**Comment by adarsh4d** [comment]
@nimitbhargava 
> Did I miss something?

Yes, as @manniL pointed out, without implementing the MouseTrap, it will only trigger the quick find in Firefox. 

I have created this site [SVG Logo](https://svg-logo.netlify.com/) without MouseTrap and see what happens when you press `/` in 

@manniL Thanks, found a new bug :)

**Comment by nimitbhargava** [comment]
@adarsh4d Thanks for explanation!
@thiyagu-7 I am interested in this task, if you plan to skip it due to some reason, I will be willingly to take it up

**Comment by thiyagu-7** [comment]
@nimitbhargava I'm planning to work on it :)

**Comment by Atinux** [comment]
Wouhou https://github.com/nuxt/nuxtjs.org/pull/247 💚
