### ISSUE TITLE
Update README to reflect how to run "prod build" locally

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxtjs.org#236]
When running the project locally (via `yarn dev`) everything works fine. But testing it via `yarn build && yarn start` or `yarn generate` fails due to the docs integration. Is this intended? The README doesn't include info about running the prod build locally (which would be important to test purgeCSS issues for example).

**Comment by Atinux** [comment]
Actually, only `yarn generate && serve dist/` works since the docs integration is aimed to be use with full static mode in production  (this is why `nuxt start` does not work).

**Comment by Atinux** [comment]
Fixed in https://github.com/nuxt/nuxtjs.org/commit/d4311e6612e67bc069821170470cfa04c71af8aa
