### ISSUE TITLE
Mobile version: h2 underline breaks in case of new line

### ISSUE THREAD

**Issue by rohitpal99** [nuxt/nuxtjs.org#242]
### Version

[v1.1.0](https://github.com/nuxtjs.org/releases/tag/v1.1.0)

### Reproduction link

[https://nuxtjs.org/faq/host-port](https://nuxtjs.org/faq/host-port)

### Steps to reproduce

Go to reproduction link and find text "With NUXT_HOST and NUXT_PORT env variables"

### What is expected ?

CSS should not break in case of new line in h2 tag

### What is actually happening?

CSS is breaking in case of new line in h2 tag

### Additional comments?

Check CSS selector: body article h2:before

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c173">#c173</a>)</em></sub></div>

**Comment by rohitpal99** [comment]
![nuxt org issue](https://user-images.githubusercontent.com/7090592/65966579-effeaa00-e47d-11e9-8e4a-61a5a3d245a4.png)

**Comment by Atinux** [comment]
Should be fixed by https://github.com/nuxt/nuxtjs.org/pull/240 :)
