### ISSUE TITLE
faq/google-analytics: HTTP 500 Failed to fetch

### ISSUE THREAD

**Issue by AGDholo** [nuxt/nuxtjs.org#256]
### Version

[v1.1.0](https://github.com/nuxtjs.org/releases/tag/v1.1.0)

### Reproduction link

[https://zh.nuxtjs.org/faq/google-analytics](https://zh.nuxtjs.org/faq/google-analytics)

### Steps to reproduce

Visit: https://zh.nuxtjs.org/faq/google-analytics

### What is expected ?

We can see a true page

### What is actually happening?

HTTP 500

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c179">#c179</a>)</em></sub></div>

**Comment by Atinux** [comment]
![Screenshot 2019-10-15 at 12 00 13](https://user-images.githubusercontent.com/904724/66821816-5df9a580-ef43-11e9-802b-008d228ec47e.png)

I can visit the page 🤔
