### ISSUE TITLE
doc: Enable to translate the top page

### ISSUE THREAD

**Issue by aytdm** [nuxt/nuxtjs.org#263]
### What problem does this feature solve?

It solve the translation problems. Some wordings on the top page are hard-coded, so I will update for translation.

### What does the proposed changes look like?

+ [x] 1. Remove unused keys and values ​​from lang.json (in nuxt/docs)
+ [x] 2. Update "welcome" section and lang.json (in nuxt/docs)
+ [ ] 3. Update "mode" section
+ [ ] 4. Update "why" section and lang.json (in nuxt/docs)
+ [ ] 5. Update "companies" section
+ [ ] 6. Update "sponsors" section and lang.json (in nuxt/docs)
+ [ ] 7. Update "newsletter form" section

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c180">#c180</a>)</em></sub></div>

**Comment by Atinux** [comment]
PR merged, step 1 completed :)

Thank you very much for your help @aytdm
