### ISSUE TITLE
Search does not work on ja.nuxtjs.org, zh.nuxtjs.org, and ko.nuxtjs.org

### ISSUE THREAD

**Issue by inouetakuya** [nuxt/nuxtjs.org#27]
The search does not work on ja.nuxtjs.org, zh.nuxtjs.org, and ko.nuxtjs.org:

![170528-0001](https://cloud.githubusercontent.com/assets/634357/26528771/2fb0079a-43ed-11e7-82bd-e8259fefafc7.png)

**Comment by alexchopin** [comment]
Thanks for the report, I will take a look on it 👍

**Comment by inouetakuya** [comment]
:pray:

**Comment by Atinux** [comment]
https://github.com/algolia/docsearch-configs/pull/228

**Comment by Atinux** [comment]
Fixed :)
