### ISSUE TITLE
Language switch in header

### ISSUE THREAD

**Issue by CyberAP** [nuxt/nuxtjs.org#272]
### What problem does this feature solve?

Since the latest redesign it became very frustrating to switch the language. Language switch has moved to footer and now you have to scroll the whole page to change it. This is very frustrating because in some countries English locale works better (it's not blocked by ISP) and some locales are missing translations for the whole pages (in that case it would be even better to suggest switching to English instead right on that page).
Would it be possible to move language switch back to the header?

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c183">#c183</a>)</em></sub></div>

**Comment by Atinux** [comment]
PR made by @Erbenos 👏
