### ISSUE TITLE
performance.prefetch does not disable the  feature

### ISSUE THREAD

**Issue by tchincc** [nuxt/nuxtjs.org#28]
```javascript
performance: {
  prefetch: false
}
```
It does not have any effect, and it still have so many `<link rel="prefetch" />` in `<head>` if I add page into the router.

**Comment by janrembold** [comment]
Same here. I tried to set performance property also in generate property. Both options have no effect on the generated markup

**Comment by pi0** [comment]
Sorry for inconveniences for lack of documentation. You may use `ssr.inject` and `ssr.shouldPreload` instead. ([docs](https://ssr.vuejs.org/en/api.html#inject))

**Comment by janrembold** [comment]
@pi0 Thanks for the quick response. I just dived into Vue.js and Nuxt. Could you give me a hint where I have to configure the inject property? I experiment with the plain nuxt/starter template. Thanks in advance!

**Comment by pi0** [comment]
You have to add it do `nuxt.config.js` file like this:
```
{
  ssr: {
     inject: false
 }
}
```

But suggest not doing this! That performance hints are really encouraged normally there should not be any problem with this.

**Comment by janrembold** [comment]
Sorry, but this configuration has no effect to the generated preload/prefetch link tags in the head.

**Comment by janrembold** [comment]
Great! :) We are getting closer. This removes the preload link tags but the prefetch tags are still injected. Any idea?
