### ISSUE TITLE
Unfold changelog by default to fix permalinks

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxtjs.org#292]
When you currently link to a subheading of a Nuxt version changelog, e.g. https://nuxtjs.org/guide/release-notes/#dx-improvements-, it won't show the corresponding text as the changelog is collapsed by default. Either unfold by default *or* unfold when linked to a heading (might be more work).

**Comment by bdrtsky** [comment]
There's also a risk of duplicate ID for subheadings. They must be unique (may be add release version to ID)

**Comment by manniL** [comment]
Good point!
