### ISSUE TITLE
Code font

### ISSUE THREAD

**Issue by infinnie** [nuxt/nuxtjs.org#3]
> ![image](https://cloud.githubusercontent.com/assets/8168391/21085249/8977c9f6-c04a-11e6-8991-6dda585addb4.png)

is rendered like:
> ![image](https://cloud.githubusercontent.com/assets/8168391/21085271/d523ed58-c04a-11e6-962f-e3124dd0bcd5.png)

Maybe a proper monospace font is needed like
> ![image](https://cloud.githubusercontent.com/assets/8168391/21085286/2b3c56d0-c04b-11e6-90e6-6ec3cd6bc635.png)

**Comment by alexchopin** [comment]
Hi,
Thanks for the reviewing, it'll be update soon 👍
