### ISSUE TITLE
/faq/google-analytics/ failed to fetch in Google Chrome. Error Code 500

### ISSUE THREAD

**Issue by IdrisN** [nuxt/nuxtjs.org#305]
### Version

[v1.1.0](https://github.com/nuxtjs.org/releases/tag/v1.1.0)

### Reproduction link

[https://nuxtjs.org/faq/google-analytics](https://nuxtjs.org/faq/google-analytics)

### Steps to reproduce

Open https://nuxtjs.org/faq/google-analytics in Google Chrome

### What is expected ?

The page content should be loaded 

### What is actually happening?

Error Code 500 - Failed to fetch

### Additional comments?

I've tried it with Chrome 80.
It worked on Safari and Firefox Developer Edition.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c199">#c199</a>)</em></sub></div>

**Comment by bdrtsky** [comment]
This is happening because Adblock detects `google-analytics` keyword in URL. Probably URL for that page should be changed.

**Comment by IdrisN** [comment]
Disabling my adblocker solved it. I agree that the route should probably be changed.

**Comment by bdrtsky** [comment]
Should be fixed now https://github.com/nuxt/nuxtjs.org/pull/362
