### ISSUE TITLE
Strange redirect when right click or ctrl+click on logo

### ISSUE THREAD

**Issue by bdrtsky** [nuxt/nuxtjs.org#309]
### Version

[v1.1.0](https://github.com/nuxtjs.org/releases/tag/v1.1.0)

### Reproduction link

[https://nuxtjs.org/api](https://nuxtjs.org/api)

### Steps to reproduce

If you navigate to https://nuxtjs.org/api and then try to right click (for example to open home page in new window) on it, then it's redirects to https://nuxtjs.org/design

If you try to ctrl + left click then it's navigates to main page in same window, while it should open new one.

### What is expected ?

Correct native navigation

### What is actually happening?

Bad navigation

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c204">#c204</a>)</em></sub></div>

**Comment by bdrtsky** [comment]
Looks like this is intended. But why?

```
@click.prevent="$router.push('/')" @click.right.stop.prevent="$router.push('/design')"
```

**Comment by Atinux** [comment]
Most people, when they right click on a logo, it's to get the image/svg, this is why I redirect to `/design`, like https://zeit.co is doing.

Actually, CMD + Click on the logo should work, so this is actually a bug on this part
