### ISSUE TITLE
Cannot deploy to AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by SoldierCorp** [nuxt/nuxtjs.org#31]
Hello!

I'm trying to deploy the dist folder and my package.json to an EB instante but it's not working, some weird errors are showing related to NodeJS. 

In this EB instance I have been deploying this same website but with VueJS 2 without NuxtJS but now I'm trying to deploy with the new structure using NuxtJS.

Do you have any idea?

**Comment by Atinux** [comment]
Wrong repo, should be on https://github.com/nuxt/nuxt.js
