### ISSUE TITLE
how can i use local json

### ISSUE THREAD

**Issue by xiao8cn** [nuxt/nuxtjs.org#32]
`async asyncData ({ params }) {
            let { data } = await axios.get('~static/test.json')
            return data
        }`

errmsg:
(node:4796) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: connect ECONNREFUSED 127.0.0.1:80

**Comment by derickruiz** [comment]
@xiao8cn Did you end up figuring this one out?

**Comment by maziarz** [comment]
I have the exact same problem with local json files. How was this problem solved?
