### ISSUE TITLE
Dark mode 404 page looks broken

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxtjs.org#327]
<img width="1615" alt="image" src="https://user-images.githubusercontent.com/640208/78355291-c13cca00-75ad-11ea-9400-14f3522a124e.png">

**Comment by bdrtsky** [comment]
![Screenshot from 2020-04-05 18-52-59](https://user-images.githubusercontent.com/45076741/78503345-b1b8af00-776e-11ea-82ef-3d8204d1308f.png)
