### ISSUE TITLE
Nuxt Searching Woes

### ISSUE THREAD

**Issue by natecox** [nuxt/nuxtjs.org#33]
I enjoy working in the Nuxt framework and have transitioned to using it for client work with my team. In general, it's fantastic, with only a few obvious pain points (SSR with vendor libraries is a notable one).

However, I do want to complain about the choice of name. I get it; it's a play on NextJS from React, and it's humorous. However, trying to find Nuxt documentation or community examples is a nightmare because Next dominates the SEO. Virtually any time I try to find something for Nuxt, Google attempts to autocorrect to Next, and I end up writing `+nuxt -next <my actual query` any time I want to find something relevant.

Is there anything we can do to help with this in general? If not, would a name change be completely out of the realm of possibility? I don't imagine we're the only group out there facing this on a regular basis.

**Comment by pi0** [comment]
@natecox Maybe that's google's fault learning more :D Actually what i attempt to search is just more related to nuxt without any suggest for next! What about triyng to search with `nuxtjs+ ...` ?

**Comment by pi0** [comment]
Also adding term "vue" should help a alot
