### ISSUE TITLE
Alert text color

### ISSUE THREAD

**Issue by gaetansenn** [nuxt/nuxtjs.org#330]
### Version

[v1.1.0](https://github.com/nuxtjs.org/releases/tag/v1.1.0)

### Reproduction link

[https://fr.nuxtjs.org/api/configuration-hooks/](https://fr.nuxtjs.org/api/configuration-hooks/)

### Steps to reproduce

Hello,

There is a problem with the text color from the alert at the top of the page.

![Screenshot 2020-04-06 at 10.41.40.png](https://cmty.s3.eu-west-1.amazonaws.com/73294699/4f0fab90-77e3-11ea-b99b-11b436d0d1da.png)

### What is expected ?

A different text color to be able to read the text

### What is actually happening?

We can't read the text

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c209">#c209</a>)</em></sub></div>

**Comment by gaetansenn** [comment]
@serggonin

**Comment by bdrtsky** [comment]
This already should be fixed with https://github.com/nuxt/nuxtjs.org/pull/307
