### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by ThibaultVlacich** [nuxt/nuxtjs.org#337]
### Version

[v1.1.0](https://github.com/nuxtjs.org/releases/tag/v1.1.0)

### Reproduction link

[https://nuxtjs.org/faq/google-analytics](https://nuxtjs.org/faq/google-analytics)

### Steps to reproduce

Go to https://nuxtjs.org/faq/google-analytics

### What is expected ?

The page appears

### What is actually happening?

A 500 error is raised

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c210">#c210</a>)</em></sub></div>

**Comment by bdrtsky** [comment]
Duplicate https://github.com/nuxt/nuxtjs.org/issues/305
