### ISSUE TITLE
Navbar does not respect safe-area-inset and overlap iPhone X Home Indicator 

### ISSUE THREAD

**Issue by mrleblanc101** [nuxt/nuxtjs.org#349]
### What problem does this feature solve?

This would improve the mobile experience on iPhone X and newer as currently the bottom Navbar does not respect safe-area-inset for the Home Indicator

### What does the proposed changes look like?

Adding a padding-bottom: env(safe-area-inset-bottom) would prevent the Home Indicator from overlapping the Navbar.

![4B8FD155-028D-4C67-9676-BC7DC1A2978A.jpeg](https://cmty.s3.eu-west-1.amazonaws.com/73294699/1e314120-8461-11ea-9054-91b04ed0aea6.jpeg)

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c214">#c214</a>)</em></sub></div>

**Comment by mrleblanc101** [comment]
I can work on this if someone gives me the go ahead. Shouldn't be too hard to fix.

**Comment by Geminii** [comment]
Hi @mrleblanc101 
You can purpose a PR for this fix :) 
Just be careful about potential regression on other device.

**Comment by mrleblanc101** [comment]
There you go #351

**Comment by bdrtsky** [comment]
Where is exactly the issue on image? We already had this before, but it was removed since it broke padding on every other device beside iPhone https://github.com/nuxt/nuxtjs.org/pull/299

**Comment by mrleblanc101** [comment]
@bdrtsky The issue it that the Navbar should not overlap the home indicator. That's why the same area inset API was created. 

![image](https://user-images.githubusercontent.com/17392251/80368791-49d02280-885b-11ea-884b-099400d833d3.png)

The old solution did not work as you added padding in a fixed height container, which reduced the height of the content. 
Ex: Container is 64px high. As you scroll, the safe-area-inset increase from 0 to  20px reducing the content height. An other solution than removing the fixed height would be to use `box-sizing: content-box;` instead of `border-box`
