### ISSUE TITLE
Dynamic Component

### ISSUE THREAD

**Issue by bhavikcex** [nuxt/nuxtjs.org#35]
Want to load component based on request

Here is my page
```
<template>
<Component :is="currentView"/>
</template>
<script>
export default {
   data () {
        return {currentView: '~/components/' + this.$route.query.country + '/content.vue'}
   }
}
</script>
```

I don't know how to do, but from above you may get an idea

**Comment by pi0** [comment]
Dynamic components coming soon in next release :) [commit](https://github.com/nuxt/nuxt.js/commit/e4e9149b5473ae081cec0a10f354da26d53e63bc). Please open nuxt related issues in nuxt.js repo instead.
