### ISSUE TITLE
Missing URLs

### ISSUE THREAD

**Issue by alexchopin** [nuxt/nuxtjs.org#36]
https://github.com/nuxt/nuxt.js/issues/1060

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c10">#c10</a>)</em></sub></div>

**Comment by digitalfrost** [comment]
Details from: nuxt/nuxt.js#1060

Resources
https://nuxtjs.org/examples/with-vuetify

page not found 404

**Comment by digitalfrost** [comment]
Can this be closed? There is no link in the left hand side menu for Vuetify.
