### ISSUE TITLE
Route transition delay

### ISSUE THREAD

**Issue by noname202** [nuxt/nuxtjs.org#365]
### Version

[v1.1.0](https://github.com/nuxtjs.org/releases/tag/v1.1.0)

### Reproduction link

[https://nuxtjs.org/](https://nuxtjs.org/)

### Steps to reproduce

Navigate the nuxtjs.org website.

### What is expected ?

Responsive user experience and almost no perceivable delays.

### What is actually happening?

When navigating the official NUXTJS website, page transitions feel kind of sluggish and there is a perceivable delay until the new page is displayed. This is especially noticable when compared to simmilar frameworks official pages such as Next.js, I had a look at the Source and it turns out that for some reason a 0.3 s CSS transition is being applied to the body element of the website. However, as far as I'm concerned, there is no visible transition animation.

```<body class="font-sans font-medium bg-light-surface dark:bg-dark-surface text-light-onSurfacePrimary dark:text-dark-onSurfacePrimary transition-colors duration-300 ease-linear ">```

```
.duration-300 {
    transition-duration: .3s;
}

.ease-linear {
    transition-timing-function: linear;
}
```

### Additional comments?

I'm not entirely sure if the delay is applied on purpose, but from my perspective it dramatically lowers the perceived performance.

Tested on Chrome Version 81 (Windows) and Safari (IOS 13.5)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c217">#c217</a>)</em></sub></div>

**Comment by bdrtsky** [comment]
What exactly does this mean "page transitions feel kind of sluggish"?

**Comment by noname202** [comment]
> What exactly does this mean "page transitions feel kind of sluggish"?

Sorry for not being more precise.  Currently, the tailwind utility classes `transition-colors`, `ease-linear`, and most importantly `duration-300`  are used for the `body `element as well as each page's `div `container. While this has (at least from what I can judge) no visible effect on route / page transitions, the 0.3 s transition duration is still applied, effectively delaying route / page transitions by 0.3 s. This results in navigating the page feeling not as fast as it should be.  

You can easily reproduce this by opening your browsers DevTools, selecting the `body `tag and unselecting the `transition-duration` property in the CSS `duration-300` class. Navigating the page should now feel much faster. Instead of unselecting you can also set it to a large value such as 3 seconds and navigate the page which makes it much more obvious that route transitions are being delayed by the CSS transition.

![image](https://user-images.githubusercontent.com/11783562/83940197-0f0ac400-a7e3-11ea-8802-5cc688fd7f3f.png)

**Comment by bdrtsky** [comment]
I don't see any difference. This has CSS property has nothing to do with page transitions. Can you record the video what exectly you mean, or describe this effect that bothers you?

**Comment by bdrtsky** [comment]
I see now. Well, this is unexpected behavior how TailwindCSS force us to us it's transition classes. It should be applied only for `background-color,border-color,color,fill,stroke` but it has this unexpected effect. Good catch.

**Comment by noname202** [comment]
Great. I have to admit that it's not super noticeable on desktop browsers. However on touch screen devices it's definitely subtracts from the perceived performance.

**Comment by bdrtsky** [comment]
> I'm not entirely sure if the delay is applied on purpose

Yes, it is in purpose, to transition color mode switches. It was done be the way Tailwind suggest to use it's utility classes for transition, but looks it is very bad practice.

**Comment by noname202** [comment]
I really believe this should be fixed. Performance is a key motivation for using a framework like Nuxt. Thus artificially delaying route transitions on the project's official website doesn't make for a good first impression. Especially when compared to something like Next.js or Gatsby.

**Comment by bdrtsky** [comment]
Page transitions actually doesn't have nothing to do with perceived performance. In practice, I saw plenty of cases when delay/loader/transition was added in purpose to not to overwhelm user with instant route navigation 😀

**Comment by noname202** [comment]
I was refering to a delay without any visual feedback. Transition animations like fade in can indeed enhance user experience.

**Comment by bdrtsky** [comment]
https://github.com/nuxt/nuxtjs.org/pull/366
