### ISSUE TITLE
How to add SSL to Nuxt

### ISSUE THREAD

**Issue by fortil** [nuxt/nuxtjs.org#37]
Hi guys
How to integrate https and nuxt?
I found several examples with express, https, etc, but doesn't work to me with nuxt.

This is my code
In the logs shows 'Started!' but doesn't shows in my navigator
```
const fs = require('fs')
const https = require('https')
const app = require('express')()
const port = process.env.PORT || 80
const Nuxt = require('nuxt')
const config = require('./nuxt.config.js')
const nuxt = new Nuxt(config)
let options = {
  key: fs.readFileSync('/etc/pki/tls/private/localhost.key'),
  cert: fs.readFileSync('/etc/pki/tls/certs/localhost.crt')
}
app.get('/sitemap.xml', require('./xml/sitemap.js'))
app.use(nuxt.render)
https.createServer(options, app).listen(port, '0.0.0.0', function () {
  console.log('Started!')
})
```

Thanks

**Comment by Atinux** [comment]
I advice you to use a proxy to handle SSL connection (see Heroku for SSL, Now.sh, etc.).

You can also use [CloudFlare](https://www.cloudflare.com/) for this, it's pretty awesome and free!
