### ISSUE TITLE
Installation page down

### ISSUE THREAD

**Issue by rgeraldporter** [nuxt/nuxtjs.org#372]
### Version

[2.12.x](https://github.com/nuxtjs.org/releases/tag/2.12.x)

### Reproduction link

[https://nuxtjs.org/guide/installation](https://nuxtjs.org/guide/installation)

### Steps to reproduce

Page worked a few minutes ago, now is down. Checked multiple browsers and asked coworkers to also check, all see the same.

### What is expected ?

Should have install instructions

### What is actually happening?

Blank page

### Additional comments?

was trying to follow instructions and they vanished

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c222">#c222</a>)</em></sub></div>

**Comment by manniL** [comment]
Should be fine again!
