### ISSUE TITLE
Extract docs server to a NPM package

### ISSUE THREAD

**Issue by ScopeyNZ** [nuxt/nuxtjs.org#385]
### What problem does this feature solve?

People (like myself) can't use Nuxt to render docs from markdown files on GitHub, without having to do all the scaffolding manually, or copying and pasting code from the nextjs.org repo. Additionally, having this functionality used independently should hopefully result in a more accessible contributor ecosystem meaning the docs module is more likely to have community contributed bugfixes and enhancements.

### What does the proposed changes look like?

Hopefully not much more than:

- Allowing the source of the docs to be configured (https://github.com/nuxt/nuxtjs.org/blob/master/modules/docs/server.js#L93)
- moving the `modules/docs` folder to it's own repo
- adding a new package on NPM
- adjusting the integration within the nuxtjs.org repo

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c225">#c225</a>)</em></sub></div>

**Comment by debs-obrien** [comment]
Thanks for your thoughts and efforts. We are releasing the new docs next week which will be using content module and all in one repo therefore much easier to work with. Once released please let us know what you think but it will be a huge improvement especially for contributing.

**Comment by ScopeyNZ** [comment]
Thanks for the feedback. I look forward to seeing the updates. I found the content module shortly after writing this and made it work for me. Thanks.
