### ISSUE TITLE
Search field in header does not work

### ISSUE THREAD

**Issue by colbygarland** [nuxt/nuxtjs.org#386]
### Version

[v1.1.0](https://github.com/nuxtjs.org/releases/tag/v1.1.0)

### Reproduction link

[https://nuxtjs.org/](https://nuxtjs.org/)

### Steps to reproduce

1. Press "/" to focus search field
2. Enter some text (for example, I searched for "async"
3. Press enter to search, or try to press the search icon

### What is expected ?

Search results are shown

### What is actually happening?

Nothing happens. No errors in console either

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c226">#c226</a>)</em></sub></div>

**Comment by debs-obrien** [comment]
this should be resolved in new version out next week
