### ISSUE TITLE
how to add babel-polyfill to webpack entry nuxt

### ISSUE THREAD

**Issue by lemonpigpig** [nuxt/nuxtjs.org#39]
why i have to add babel-polyfill,my pc application only work in chrome and firefox,other like qq browser cannot load.i found that js file have a error,and some es6 still exist, my config is 
 build: {
    babel: {
      presets: ['es2015', 'stage-2'],
      'plugins': ['transform-runtime']
    },
    extractCSS: true,
    vendor: [
      'babel-polyfill',
      'eventsource-polyfill',
      'swiper',
      'axios'
    ]}

but after build i found nothing have change, tell my the right way,my application will online soon,i need your help really, thx

**Comment by pi0** [comment]
Hi. Please don't make duplicate issues & track state at nuxt/nuxt.js#1118

**Comment by lemonpigpig** [comment]
sorry

**Comment by pi0** [comment]
No problem bro ❤ We just try to organize things to help issues resolved faster.
