### ISSUE TITLE
[dev] publish assets in an open format

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxtjs.org#398]
Raw assets for diagrams is not published (or probably I'm missing). By publishing, contributors can modify them to update the docs. Ideally, we may also automate static assets generation from the source.

**Comment by debs-obrien** [comment]
This is a great idea and would make it much easier to make minor changes when we update. What do you suggest @pi0, a folder called raw in static?

@krutie what do you think? Is it possible to upload the raw versions?

**Comment by pi0** [comment]
I've seen some publish as "artworks" with CC license. Using static or assets and including instructions in repo readme would be fantastic!

**Comment by Krutie** [comment]
@debs-obrien Sorry, I'm little lost here. But, does raw versions mean editable versions? 
If yes, then I can invite interested team member (by email address) in my Lucidchart account, and then he/she can edit the document.

@pi0 Can you show me such repo as an example, please?

**Comment by debs-obrien** [comment]
Yes I think what Pooya means is if we dave the raw version say like photoshop would be a psd file then we modify the psd file and generate the pdf for example. Which sounds great but I think that might now work for Lucid as its editable version is in Lucid or can we save the Lucid editable version in a folder in the repo so that people can contribute and make minor changes when we have updates. Yeah I am not sure how it would work and if Lucid requires license etc. what do you think would work best

**Comment by Krutie** [comment]
Hey @debs-obrien & @pi0 I have created a repo to test out the _raw-version-idea_ as mentioned above.

Here's the test repo, https://github.com/Krutie/nuxt-diagrams Please try editing the diagram as per the instructions found in README file. Let me know if anything doesn't make sense.

If this works out as expected, then yes, we can add `.drawio` files of each diagrams into `static/raw` folder along with the README file with instructions.

> Ideally, we may also automate static assets generation from the source.

I'm looking into this, but so far I haven't been able to find any API or CLI utility which we can use to automate the SVG generation from the source file.

At this point, it looks like, whoever update or contribute to the diagram, is responsible to export the SVG and provide it as a part of the pull request.

**Comment by debs-obrien** [comment]
closing this issue. I think this solution works fine and if others translate the .drawio file then they have to export as svg. seems ok to me

**Comment by pi0** [comment]
@debs-obrien Is there any link to Krutie's repo in docs?

**Comment by debs-obrien** [comment]
in static folder we have the images under guides and in the raw folder there is the one raw file
