### ISSUE TITLE
[dev] wrong context

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxtjs.org#399]
Checking latest version of [context](https://github.com/Krutie/nuxtjs.org/blob/0cfae1ee7755f28cddd92695c0decddf64bd43cb/static/guides/context.jpeg), these are not part of real nuxt context: `env`  and `isDev` are not part of nuxt context object but provided by webpack during build by usage for `process.*`. Maybe would be better to remove them to avoid misunderstanding or add a notice?

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtjs.org/issues/c229">#c229</a>)</em></sub></div>

**Comment by Krutie** [comment]
@pi0 Will update soon. 👍

**Comment by Krutie** [comment]
Hey @pi0 I have updated the Context diagram as per your feedback above. Instead of removal, I have gone with adding a new note. You can see it on the top-left box against asterisk `*` character.
CC: @debs-obrien

![Nuxt Context 2020 v2](https://cdn.krutiepatel.com/2020-07/nuxt-2-14-context-v2.svg)

**Comment by debs-obrien** [comment]
looks great 😊

**Comment by pi0** [comment]
Looking much better @Krutie :100: Maybe mentioning "during build as `process.*`" can make it even more readable but already awesome change!

**Comment by Krutie** [comment]
@pi0 It's done! 
PR sent - https://github.com/nuxt/nuxtjs.org/pull/444 Let me know if any issue.
![Nuxt Context 2020 v3](https://cdn.krutiepatel.com/2020-07/nuxt-2-14-context-v3.svg)

**Comment by debs-obrien** [comment]
merged
