### ISSUE TITLE
The Affix can not scroll

### ISSUE THREAD

**Issue by k55k32** [nuxt/nuxtjs.org#4]
I brower the  [nuxt(vue-store-documents)](https://nuxtjs.org/guide/vuex-store/)
The left nav can not be scroll
I remove the css style`overflow-y: visible;`  on `Affix.vue` [# line 139 ](https://github.com/nuxt/nuxtjs.org/blob/master/components/Affix.vue#L139)
Now is worked. 👍

**Comment by alexchopin** [comment]
Hi,

@k55k32, thanks for the feedback, it's fixed.

@jvandenaardweg, actually we use it for mobile toggling the Affix component with `:class` so it's just css who handle responsive. We need it even if it useless on desktop.
