### ISSUE TITLE
Brazilian portuguese translation

### ISSUE THREAD

**Issue by galvez** [nuxt/nuxtjs.org#40]
@Atinux How can I go about translating this website to Brazilian portuguese? Just fork it and let you do the rest?

**Comment by alexchopin** [comment]
Hi @galvez, we are working on the v1 doc, so we'll keep you in touch when the doc will be finished in English first.

**Comment by alexchopin** [comment]
I close this issue because it's related to [docs repo](https://github.com/nuxt/docs).
