### ISSUE TITLE
[dev] modules diagram improvements

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxtjs.org#400]
Checking with [latest](https://github.com/nuxt/nuxtjs.org/blob/7a87b2c3ad6115d979fcaee8e0e89352702b87e3/static/guides/modules.jpg) version:

- `build.vendor` is not effective since nuxt 2.0 (module contamination created vendor and shared chunks automatically)
- "modules served thought npm packages and also be accessed via plugins" --> This is totally wrong because modules and plugins are not ina same context but can also provide plugins. Wording could be like services added by other plugins using `$inject` or so?

Some suggestions

- Maybe would be better advising `plugin.client.js` (and also `.server.js`) instead of `{ ssr: false }`
- It would be probably better to use `export default` for `nuxt.config` (and removing `.js` to simplify and typescript users)
- Maybe nice including `buildModules`

**Comment by debs-obrien** [comment]
nice feedback @pi0 will leave this to @krutie as we don't have access to change the diagram. 
Also @pi0  as per question in discord. Does it make sense to split this into 3 images that can then be used in the corresponding pages: plugins, modules and serverMiddleware instead of repeating the same image on these pages?

**Comment by Krutie** [comment]
`module, plugins & serverMiddleware` diagram was created long time ago, it's due for revision anyways. All good points above, @pi0 
I'll make the revision soon.

**Comment by Krutie** [comment]
Hey @debs-obrien & @pi0 I have created **Plugin** diagram and updated it according to Pooya's comments above. 
- Plugin has enough information to become standalone diagram on its own. So, the module-explainer diagram will be separate to this one. 
- This version is created using Draw.io, and exported as an SVG (45kb).

Both of your feedback is most welcome.
![Nuxt Plugins](https://nuxt-diagrams-temp.s3-ap-southeast-2.amazonaws.com/plugins.svg)

**Comment by debs-obrien** [comment]
hey @Krutie after meeting yesterday with @pi0 this is good to go for pr to guides to replace old image. Then just create a raw folder inside static folder and add the raw file there. Amazing work. well done

**Comment by Krutie** [comment]
Thanks @debs-obrien Next up is the image for _Modules_ page. I'll keep you both updated as I progress through. 
cc: @pi0

**Comment by jefrydco** [comment]
Hi sorry, for jump in. For this kind of diagram, do we need to translate it as well? Since it also contains english text description in it

**Comment by debs-obrien** [comment]
Hey @jefrydco that is a great question. To be honest it is not necessary but it can be done as the raw file is included so I will leave that up to anyone who wants to give it a go. It's a nice extra but it's not a must for the docs to be released in another language.

**Comment by oiagorodrigues** [comment]
I do like the idea of translating the images as well. How did you do the diagrams @debs-obrien @Krutie ?

**Comment by debs-obrien** [comment]
@oiagorodrigues So you will find the raw version in the static folder. We only have 1 that is editable at the moment plugins.draw.io. From there you will need to open the file in finder and then you can drag and drop it into - https://app.diagrams.net/. Then make your changes and export as svg and upload to static folder under guides with perhaps an es folder inside the guides folder and then just modify the link in the docs to serve that image

**Comment by oiagorodrigues** [comment]
By "es folder" you mean a language folder?

**Comment by debs-obrien** [comment]
correct sorry, pt in your case @oiagorodrigues

**Comment by oiagorodrigues** [comment]
Awesome. I'll do that as soon as I have some time.

**Comment by Krutie** [comment]
> Thanks @debs-obrien
> 
> * [x]  Next up is the image for _Modules_ page.
> 
> I'll keep you both updated as I progress through.
> cc: @pi0

@debs-obrien and @pi0:

The [Nuxt Modules Diagram](https://cdn.krutiepatel.com/2020-09/modules.svg) (SVG, 47kb) is ready for review.

This diagram will replace the one we see on [Directory structure > modules](https://nuxtjs.org/guides/directory-structure/modules) page at the moment.

**Comment by debs-obrien** [comment]
Looks amazing. Well done. Will wait for Pooyas review but really great job

**Comment by debs-obrien** [comment]
@pi0 this got lost in the noise of the chat. can you check this diagram please

**Comment by pi0** [comment]
It seems much much better now well done @Krutie. Checking [this](https://cdn.krutiepatel.com/2020-09/modules.svg) version, a small point about second example of "async modules", they do not get `$http` as first param. It can be something like this:

```js
export default functon asyncModule() {
  return fetch().then(response => { ... })
}
```

**Comment by Krutie** [comment]
> ... they do not get $http as first param

In that case, this [example](https://nuxtjs.org/guides/directory-structure/modules#return-a-promise) needs to be updated as well to reflect what @pi0 is saying. Am I right?

**Comment by Krutie** [comment]
@debs-obrien @pi0 The [modules diagram](https://cdn.krutiepatel.com/2020-10/modules.svg) has been updated as per Pooya's feedback. If it's good to go, let me know and I can make a PR.

**Comment by debs-obrien** [comment]
Thanks @Krutie, looks good to me but will see what @pi0 says. Also regarding your comment above will let Pooya answer that too. When you make pr if changing extension can you make sure to do a search and replace so other langs also have the correct file. I fixed the last one but would be easier to have other langs covered in pr as we have a few that are now live. Thanks

**Comment by Krutie** [comment]
@debs-obrien My bad! Sincere apologies for the mistake. I will make sure to check throughly into other language files from next time onwards.
