### ISSUE TITLE
problem at middleware

### ISSUE THREAD

**Issue by JermeyYann** [nuxt/nuxtjs.org#44]
If i  write wrong `proxy`，`check-auth` was executed 3362 times in one request

- code & result

![image](https://user-images.githubusercontent.com/13900367/28653540-a7bf47bc-72c0-11e7-9ac8-f635f10ac5fe.png)

![image](https://user-images.githubusercontent.com/13900367/28652995-b5188bb0-72bd-11e7-932a-bf44bd793737.png)

**Comment by alexchopin** [comment]
Not related to this repo.
