### ISSUE TITLE
Contribution guide

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxtjs.org#45]
As history showed Many people are making wrong issues here instead of [nuxt.js](https://github.com/nuxt/nuxt.js) main repo. So i suggest having a `.github/ISSUE_TEMPLATE.md` 
 like [vue](https://raw.githubusercontent.com/vuejs/vue/dev/.github/ISSUE_TEMPLATE.md) which shows a message when creating new Issues.

/CC @alexchopin @Atinux

**Comment by Atinux** [comment]
@pi0 it's planned with the new version of nuxtjs.org :)

**Comment by pi0** [comment]
Great! So closing this one :D
