### ISSUE TITLE
Vue components in node_modules are not compiled on server-side

### ISSUE THREAD

**Issue by xkjyeah** [nuxt/nuxtjs.org#46]
I created a simple package named `myp`:
**nuxt.config.js**
```js
{
  ...[omitted],
  plugins: ['~/plugins/sample.js']
}
```
**plugins/sample.js**
```js
import HisPlugin from 'myp'
Vue.component('HisPlugin', HisPlugin)
```
**node_modules/myp/package.json**
```js
{
  ...[omitted],
  "main": "test.vue"
}
```
**node_modules/myp/test.vue**
```vue
<template>
  <div class="my-plugin">
    It works!
  </div>
</template>
<style>
.my-plugin {
  font-size: 200%;
}
</style>
```

And the following error message:
```
C:\Users\Daniel\Desktop\ssrtest\node_modules\myp\test.vue:1
(function (exports, require, module, __filename, __dirname) { <template>
                                                              ^
SyntaxError: Unexpected token <
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
```

This presumably comes from the server-side renderer, which does not recognize *.vue files. Is it possible to get the server-side renderer to recognize them?

Some libraries export .vue files, and it is the recommended approach by Evan You (https://forum-archive.vuejs.org/topic/1203/how-to-bundle-a-set-of-vue-components-efficiently/4)

**Comment by hack2root** [comment]
It is not supposed to be built from node_modules/ or bower_components/ folder. There is a special plugins/ folder aside to the workspace folder (where the nuxt.config.js resides)

**Comment by makssherstobitow** [comment]
It's solved here [https://github.com/vuejs/vue-jest/issues/5](https://github.com/vuejs/vue-jest/issues/5).
