### ISSUE TITLE
Dedicated Resources Page (Branding)

### ISSUE THREAD

**Issue by alexchopin** [nuxt/nuxtjs.org#48]
Related to https://github.com/nuxt/nuxt.js/issues/1226

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c41">#c41</a>)</em></sub></div>

**Comment by manniL** [comment]
Maybe an own repo (like https://github.com/vuejs/art) would be good for that :thinking:

**Comment by manniL** [comment]
Friendly reminder that this is highly needed :speak_no_evil:

**Comment by manniL** [comment]
https://nuxtjs.org/design
