### ISSUE TITLE
Server Side Rendering for components called from layouts

### ISSUE THREAD

**Issue by nyl-auster** [nuxt/nuxtjs.org#51]
Hello ! on my site (https://yineo.fr/), my right sidebar is a component called from **layouts/default.vue**

Because i don't want to call it in every page component. 

So my sidebar with last articles is not server side rendered and google bot can not see it ( see picture below, the left one is what google bot see and probably index )

How can i have server side rendering for my "Sidebar" Component called from **layouts/default.vue** ( code below the picture ) ?
thanks !

<img width="1101" alt="capture d ecran 2017-08-12 a 04 24 47" src="https://user-images.githubusercontent.com/335495/29237021-c3c1c262-7f15-11e7-9267-b2170831a9cb.png">

```html
<!-- main layout -->
<template>
  <div>
    <AppNavigation />
    <AppHeader/>
  
    <div class="container">
      <div class="columns">
  
        <div class="column is-two-thirds">
          <nuxt/>
        </div>
  
        <div class="column">
          <section class="section">
            <TwitterFollowMe/>
            <hr/>
            <h2 class="title is-2">Derniers billets</h2>
            <PostsSidebar :posts="posts" />
          </section>
        </div>
  
      </div>
    </div>
    <AppFooter />
  </div>
</template>

<script>
import AppHeader from '~/components/AppHeader'
import AppNavigation from '~/components/AppNavigation'
import AppFooter from '~/components/AppFooter'
import TwitterFollowMe from '~/components/TwitterFollowMe'
import PostsSidebar from '~/components/PostsSidebar'
import { getPosts } from '~/services/wpContentApi'

export default {
  components: { AppHeader, AppNavigation, AppFooter, TwitterFollowMe, PostsSidebar },
  data () {
    return {
      posts: []
    }
  },
  async created () {
    this.posts = await getPosts(20)
  }
}
</script>
```

**Comment by galvez** [comment]
asyncData() doesn't work in layouts AFAIK. And you should use the nuxtjs
repo to open issues like this ;)

**Comment by nyl-auster** [comment]
@galvez oups wrong repo :D Closing this one and re-opening on nuxt 

i know about asyncData() , but maybe there is an available workaround : https://github.com/nuxt/nuxt.js/issues/1351
