### ISSUE TITLE
Wrong section for `modulesDir`

### ISSUE THREAD

**Issue by pi0** [nuxt/nuxtjs.org#531]
`modulesDir` is documented in [modules](https://nuxtjs.org/guides/directory-structure/modules) section where as it is a general [nuxt-config](https://nuxtjs.org/guides/directory-structure/nuxt-config) option used for (advanced) modifying **node_modules** search path. Naming may be improved.

**Comment by debs-obrien** [comment]
https://github.com/nuxt/nuxtjs.org/pull/541
