### ISSUE TITLE
[Spanish] translate new guides

### ISSUE THREAD

**Issue by debs-obrien** [nuxt/nuxtjs.org#543]
Looking for help to translate our website to Spanish. It has already been setup but we would love some help translating the guides folder. See the readMe for info on how to translate our site: https://github.com/nuxt/nuxtjs.org

Feel free to just take one page and submit a pr. make sure you also tick the box in the list below. Or take on the whole project and just create a draft pr and we will merge it when it is finished.

i18n configuration

- [x]  i18n file
- [x]  i18n block on nuxt.config

📝 guides -> components glossary

- [x]  pages-fetch.md
- [x]  pages-head.md
- [x]  pages-key.md
- [x]  pages-layout.md
- [x]  pages-loading.md
- [x]  pages-middleware.md
- [x]  pages-scrolltotop.md
- [x]  pages-transition.md
- [x]  pages-validate.md
- [x]  pages-watchquery.md

📝 guides -> concepts

- [x]  context-helpers.md
- [x]  nuxt-lifecycle.md
- [x]  server-side-rendering.md
- [x]  static-site-generation.md
- [x]  views.md

📝 guides -> configuration glossary
 

- [x] configuration-build.md
- [x]  configuration-generate.md
- [x]  configuration-render.md
- [x]  configuration-server.md
- [x]  configuration-telemetry.md
- [x]  configuration-router.md
- [x]  configuration-server-middleware.md
- [x]  configuration-transition.md
- [x]  configuration-builddir.md
- [x]  configuration-cli.md
- [x]  configuration-components.md
- [x]  configuration-css.md
- [x]  configuration-dev.md
- [x]  configuration-dir.md
- [x]  configuration-env.md
- [x]  configuration-extend-plugins.md
- [x]  configuration-global-name.md
- [x]  configuration-head.md
- [x]  configuration-hooks.md
- [x]  configuration-ignore.md
- [x]  configuration-loading.md
- [x]  configuration-loading-indicator.md
- [x]  configuration-mode.md
- [x]  configuration-modern.md
- [x]  configuration-modules.md
- [x]  configuration-modulesdir.md
- [x]  configuration-plugins.md
- [x]  configuration-rootdir.md
- [x]  configuration-runtime-config.md
- [x]  configuration-srcdir.md
- [x]  configuration-target.md
- [x]  configuration-vue-config.md
- [x]  configuration-watch.md
- [x]  configuration-watchers.md

📝 guides -> directory structure

- [x]  assets.md
- [x]  components.md
- [x]  content.md
- [x]  dist.md
- [x]  layouts.md
- [x]  middleware.md
- [x]  modules.md
- [x]  nuxt.md
- [x]  nuxt-config.md
- [x]  pages.md
- [x]  plugins.md
- [x]  static.md
- [x]  store.md

📝 guides -> features

- [x]  configuration.md
- [x]  data-fetching.md
- [x]  deployment-targets.md
- [x]  file-system-routing.md
- [x]  live-preview.md
- [x]  loading.md
- [x]  meta-tags-seo.md
- [x]  nuxt-components.md
- [x]  rendering-modes.md
- [x]  transitions.md

📝 guides -> get-started

- [x]  conclusion.md
- [x]  directory-structure.md
- [x]  installation.md
- [x]  routing.md
- [x]  upgrading.md

📝 guides -> internals glossary

- [x]  $nuxt.md
- [x]  context.md
- [x]  internals.md
- [x]  internals-builder.md
- [x]  internals-generator.md
- [x]  internals-module-container.md
- [x]  internals-nuxt.md
- [x]  internals-renderer.md
- [x]  nuxt.md
- [x]  nuxt-render.md
- [x]  nuxt-render-and-get-window.md
- [x]  nuxt-render-route.md

**Comment by alvarosaburido** [comment]
Hi Debbie, I can contribute, only one question, is _one page - one PR_ or I can take several pages at once?. Also, do you have any special format for branch names  and commit messages?

**Comment by debs-obrien** [comment]
hey, thanks. you can take as many pages as you like. What I would do is mark the check box of the ones you are going to do so that noone else spends time doing the same ones then just work away on a branch for example feat/translate-spanish or similar for commit messages you can just put docs: translate spanish or similar. Feel free to create a draft pr and only merge when you are finished or submit each page. up to you. depends on your time available and what works best for you. but merging frequently will allow others to see in dev what has been done. it will only go live when it is all finished so in prod you won't see any changes till we press the magic button 😉 thanks @alvarosaburido and anyone else who would like to jump on board.

**Comment by alvarosaburido** [comment]
I will take care of: 
- [x]  pages-fetch.md
- [x]  pages-head.md

Not sure why I can't check the list  you provide 🤷

**Comment by CristalT** [comment]
Hi @debs-obrien 
I'm in a similar situation of @alvarosaburido I don't know how to check the issue's list. I'm translating:

- pages-key.md
- pages-layout.md

**Comment by febrihidayan** [comment]
It can be done, try cloning

**Comment by alvarosaburido** [comment]
> It can be done, try cloning

@febrihidayan what do you mean by cloning? I guess is more a restriction to edit someone else's comment

**Comment by debs-obrien** [comment]
perhaps it is. never tried it

**Comment by CristalT** [comment]
I see somes todo items checked, who did it? How?

**Comment by alvaroOnCode** [comment]
> I see somes todo items checked, who did it? How?

Same here

**Comment by alvaroOnCode** [comment]
I am translating the guides/get-started  directory in case someone else is on it

**Comment by debs-obrien** [comment]
I did it as not sure if you all can 🤷‍♀️

**Comment by debs-obrien** [comment]
ok @alvaroOnCode I ticked them off so they are all yours.

**Comment by CristalT** [comment]
ok @debs-obrien to make it easer, could you tick "guides -> concepts" items? I'll be translating them.

**Comment by alvarosaburido** [comment]
@debs-obrien please check: guides -> components glossary->  pages-fetch.md merged here https://github.com/nuxt/nuxtjs.org/pull/581

**Comment by CristalT** [comment]
I have a question for traducers @alvarosaburido and @alvaroOnCode 
Are you writing in formal or informal spanish? (Usted vs Tu)
Just to unify criteria.

**Comment by alvarosaburido** [comment]
@CristalT I think formal is more adequate for documentation.  Im using "vuestra/o" normally. "Usar" por "utilizar". And so on.

**Comment by alvaroOnCode** [comment]
> I have a question for traducers @alvarosaburido and @alvaroOnCode
> Are you writing in formal or informal spanish? (Usted vs Tu)
> Just to unify criteria.

I'm using **Tú** not Usted, I don't think it's necessary to use formal Spanish. I use formal Spanish when I talk to old people to show respect mostly but it sounds weird to me in technical documentation. But that's my opinion.

**Comment by CristalT** [comment]
I'm accord with @alvaroOnCode 
I think that if we use the informal way, we could achieve a more friendly documentation.

**Comment by debs-obrien** [comment]
yes tu instead of usted would be better. Usted is way too formal in Spanish in my opinion. I don't think I have every used Usted

**Comment by agnelnieves** [comment]
Taking care of
📝 guides -> directory structure

- [ ] assets.md
- [ ] components.md
- [ ] layouts.md
- [ ] pages.md

**Comment by mblayer** [comment]
I will take care of

📝 guides -> components glossary
   pages-loading.md
   pages-middleware.md
   pages-scrolltotop.md

**Comment by rsdiaz** [comment]
I will take care of

- [ ] 18n file

**Comment by rodzy** [comment]
Hi, from now I will take care of:

📝 guides -> internals glossary

- [x] $nuxt.md
- [x] context.md
- [x] internals.md
- [x] internals-builder.md
- [x] internals-generator.md
- [x] internals-module-container.md

😄

**Comment by matias220510** [comment]
Hi @debs-obrien ! I can work on these:

📝 guides -> features

- [ ] configuration.md
- [ ] data-fetching.md
- [ ] deployment-targets.md
- [ ] file-system-routing.md
- [ ] live-preview.md
- [ ] loading.md
- [ ] meta-tags-seo.md
- [ ] nuxt-components.md
- [ ] rendering-modes.md
- [ ] transitions.md

Could you please thick them for me?
Thanks!

**Comment by debs-obrien** [comment]
sure @matias220510 fantastic thanks. make sure you pull latest changes from master for live-preview as we just pushed some changes to that page which will be live shortly.

**Comment by Dawntraoz** [comment]
Hi folks, I will take care of the following pages, we are almost there!! So hard work here 😍

- [ ] configuration-env.md
- [ ] configuration-extend-plugins.md
- [ ] configuration-global-name.md
- [ ] configuration-head.md

**Comment by kinxos** [comment]
Hi everyone. I'm going to take care of the following four pages. Ya casi está!

- [x] configuration-target.md
- [x] configuration-vue-config.md
- [x] configuration-watch.md
- [x] configuration-watchers.md

**Comment by krysal** [comment]
Hi hi! Has anyone taken these files? If not, I can help translate them.
- [ ] configuration-rootdir.md
- [ ] configuration-runtime-config.md
- [ ] configuration-srcdir.md

**Comment by alvarosaburido** [comment]
@kinxos So the normal process to do a PR for any repository is:

**Comment by kinxos** [comment]
Thanks @alvarosaburido So I have to start over and do it right... Thanks a lot!

**Comment by kinxos** [comment]
@alvarosaburido @debs-obrien this is happening to me when I try to push my changes. do I need to set anything in github for the push to work?
<img width="610" alt="Captura de pantalla 2020-09-03 a las 17 21 33" src="https://user-images.githubusercontent.com/971466/92141145-f4f47800-ee09-11ea-8cd6-b0a26df0a80b.png">

**Comment by kinxos** [comment]
@alvarosaburido @debs-obrien don't worry, I already got it working. my fault.

**Comment by kinxos** [comment]
@alvarosaburido Pull request created! (checks are still in progress). I wanted to thank you for taking the time to make such a detailed explanation of the process. And yes, it's really cool that I started contributing, especially when we're talking about Nuxt! Thanks again!

**Comment by Dawntraoz** [comment]
Taking care of:
- [x] configuration-mode.md
- [x] configuration-modules.md
- [x] configuration-modulesdir.md
- [x] configuration-plugins.md

**Comment by kinxos** [comment]
I'm gonna take care of:

- [ ] configuration-hooks.md
- [ ] configuration-ignore.md
- [ ] configuration-loading.md
- [ ] configuration-loading-indicator.md

**Comment by kinxos** [comment]
Now taking care of:

- [ ] configuration-dev.md
- [ ] configuration-dir.md
- [ ] configuration-modern.md

**Comment by ernmo** [comment]
Hi, do you still need any help with this translation?

**Comment by agnelnieves** [comment]
> Hi, do you still need any help with this translation? 

@ernmo i believe there are some items left in the directory-structure

**Comment by ernmo** [comment]
If nobody is doing the unticked ones, I can help with those
![image](https://user-images.githubusercontent.com/37050904/92546953-67ee5c00-f219-11ea-8cb6-b58414dd99bc.png)

**Comment by debs-obrien** [comment]
Also this pr is still in draft and you might be able to help with it or take some of the pages that are not done. https://github.com/nuxt/nuxtjs.org/pull/637

**Comment by matias220510** [comment]
> Also this pr is still in draft and you might be able to help with it or take some of the pages that are not done. #637

Hi @debs-obrien pr status updated 😃 It's a big section. sorry xD!

**Comment by ernmo** [comment]
> > Also this pr is still in draft and you might be able to help with it or take some of the pages that are not done. #637
> 
> Hi @debs-obrien pr status updated 😃 It's a big section. sorry xD!
> 
> If someone wants to pick one of these, go ahead. Currently working on configuration.md and loading.md section.
> 
> guides -> features
> 
> * [ ]  configuration.md -> Work in progress
> * [x]  data-fetching.md
> * [x]  deployment-targets.md
> * [x]  file-system-routing.md
> * [ ]  live-preview.md
> * [ ]  loading.md -> Work in progress
> * [x]  meta-tags-seo.md
> * [ ]  nuxt-components.md
> * [x]  rendering-modes.md
> * [ ]  transitions.md

Is it OK if I take the Nuxt-components.md? Thanks!

**Comment by matias220510** [comment]
> > > Also this pr is still in draft and you might be able to help with it or take some of the pages that are not done. #637
> > 
> > 
> > Hi @debs-obrien pr status updated 😃 It's a big section. sorry xD!
> > If someone wants to pick one of these, go ahead. Currently working on configuration.md and loading.md section.
> > guides -> features
> > 
> > * [ ]   configuration.md -> Work in progress
> > * [x]   data-fetching.md
> > * [x]   deployment-targets.md
> > * [x]   file-system-routing.md
> > * [ ]   live-preview.md
> > * [ ]   loading.md -> Work in progress
> > * [x]   meta-tags-seo.md
> > * [ ]   nuxt-components.md
> > * [x]   rendering-modes.md
> > * [ ]   transitions.md
> 
> Is it OK if I take the Nuxt-components.md? Thanks!

Of course @ernmo ! Thanks!

**Comment by FelixMor** [comment]
Hi, @debs-obrien and @matias220510. I've just completed nuxt-components.md  (guides -> features ->nuxt-components.md). I've submitted PR as well.

**Comment by krysal** [comment]
We're almost done! ✨ I'll take care of:

:memo: guides -> directory structure
- [x] dist
- [x] middleware
- [x] store

**Comment by agnelnieves** [comment]
@krysal 

I worked on these dist and middleware, check this PR

- [x] assets.md
- [x] components.md
- [x] layouts.md
- [x] pages.md
- [x] plugins.md
- [x] middleware.md
- [x] nuxt.md
- [x] static.md
- [x] dist.md

Pull Request: https://github.com/nuxt/nuxtjs.org/pull/596

I think the tasks were not up to date @debs-obrien idk if this is you can take care of, i wasnt able to tick the checkboxes

**Comment by debs-obrien** [comment]
ok cool updated

**Comment by krysal** [comment]
@agnelnieves oh, cool! Then I can work on **store** and **content** (directory structure).

**Comment by debs-obrien** [comment]
Perfect @krysal 😃 once you fork the project just make sure the page isn't already there. Looking forward to releasing the Spanish docs

**Comment by JoshDev1205** [comment]
Taking care of:

- [x] store

**Comment by alvarosaburido** [comment]
Nice, almost there guys

**Comment by krysal** [comment]
@JoshDev1205 `guides/directory-structure/store.md` file is already translated on #705, just waiting for merge. What remains to do is the `modules.md` file.

**Comment by debs-obrien** [comment]
Just reviewing so we can release spanish version. Here is what I have found to be missing incase anyone wants to translate it:
/guides/concepts/views

**Comment by FelixMor** [comment]
Hi, I'll work on: /guides/concepts/views

**Comment by JoshDev1205** [comment]
Thanks  @krysal for your response.

I will work on  /guides/directory-structure/modules

**Comment by Kronhyx** [comment]
Hi @debs-obrien , I`ll work on :
:memo: guides -> directory structure
- [x] nuxt-config.md

**Comment by josewhitetower** [comment]
I'll take care of
📝 guides -> concepts
 
- [ ]  server-side-rendering.md

**Comment by d4g0** [comment]
I will like to do :
server-side-rendering.md

**Comment by vborras** [comment]
Hi! I'll go with /guides/features/rendering-modes

**Comment by glpzzz** [comment]
/guides/concepts/server-side-rendering done

**Comment by glpzzz** [comment]
working on /guides/concepts/views

**Comment by debs-obrien** [comment]
hi @glpzzz please check comments above as someone had already translated the server-side-rendering one and someone has commented that they are working on the views one. so as to not to have 2 people translate the same page it might be a better idea to take one that someone has Not said they will do. If after a while we see they never got round to doing it we can then move forward with it. Thanks for your amazing work. If you have already done the views one then please make a comment referencing the person that has said they will do it so they don't then go and spend time doing something that is already done. Thanks so much. I know this system is not ideal so don't worry, we are all learning 😊

**Comment by glpzzz** [comment]
Ups. Sorry for the duplicated work. Now I stop (3am here) as not a lot of advance on views file yet. When I return I check if there is something left. Spanish is almost done!

**Comment by vborras** [comment]
I'm working on /guides/configuration-glossary/configuration-mode :)

**Comment by glpzzz** [comment]
How to know what is left? I have some advance on views.md

**Comment by debs-obrien** [comment]
Great question. I have just added labels so we can filter by label so when adding a pr just add the spanish label and we can see what has been done and what hasn't https://github.com/nuxt/nuxtjs.org/pulls?q=is%3Aopen+is%3Apr+label%3Aspanish
I think you can go ahead @glpzzz remember you can always submit work as a draft and that way people can also see it is being worked on. There are now a few pages in review and only 3 missing

- [ ]  /guides/concepts/views
- [ ]  /guides/directory-structure/modules
- [ ]  /guides/concepts/static-site-generation

**Comment by glpzzz** [comment]
Spanish speakers. How to translate layout? I don't have an spanish word for this :cry:

**Comment by agnelnieves** [comment]
> Spanish speakers. How to translate layout? I don't have an spanish word for this 😢

I left it as `layout`, since nuxt's directory contains layout anyways. Only word that comes to mind is `Plantillas de Diseño` but i think it might be a bit missleading

**Comment by glpzzz** [comment]
> > Spanish speakers. How to translate layout? I don't have an spanish word for this cry
> 
> I left it as `layout`, since nuxt's directory contains layout anyways. Only word that comes to mind is `Plantillas de Diseño` but i think it might be a bit misleading, cause it can also mean design templates

I'm using plantilla for template and diseño for layout. The first time I wrote Diseños (layouts)

**Comment by agnelnieves** [comment]
Well, as long as it's consistent i think it should be fine. I also try to include the equivalent in english the first time it gets mentioned. For example:

El directorio de diseños (`layout`), ...

**Comment by glpzzz** [comment]
@debs-obrien I uploaded the views file

**Comment by glpzzz** [comment]
> I will like to do :
> static-site-generation.md

Hi! Who are you going with this one?

**Comment by d4g0** [comment]
Hey @glpzzz i just have sended the pull request.

**Comment by glpzzz** [comment]
> Hey @glpzzz i just have sended the pull request.

Perfect, I didn't touch that one. I started with modules. Its looong

**Comment by glpzzz** [comment]
Uploaded a partial modules translation

**Comment by glpzzz** [comment]
modules is almost done. Can someone take the questions at the beginning?

**Comment by d4g0** [comment]
hey @agnelnieves  you are right, there is no palabra for layout, the most similar meaning in spanish i think it  is   " forma  de disponer u organizar "(not a solo word). I think diseño goes beyond wath you  really want to say with layout, but defently is better than nothing.

**Comment by Kronhyx** [comment]
@glpzzz  
> modules is almost done. Can someone take the questions at the beginning?

exactly what question? that of `layouts`?
in that case I think you should leave it as `layouts`

There are other words like (ej: `asere` :smile: :smile: :smile:  ) that do not have such an exact translation and it is better to leave them as such

**Comment by glpzzz** [comment]
> @glpzzz
> 
> > modules is almost done. Can someone take the questions at the beginning?
> 
> exactly what question? that of `layouts`?
> in that case I think you should leave it as `layouts`
> 
> There are other words like (ej: `asere`    ) that do not have such an exact translation and it is better to leave them as such

hahaha. asere on github. that's cool. No bro. I mean the questions at the beginning of the file. You know, there are questions and each one with options. Its like a test.

**Comment by Kronhyx** [comment]
@glpzzz I think there are only `views.md` left.

**Comment by glpzzz** [comment]
> @glpzzz I think there is only `views.md` left.

@Kronhyx , @d4g0 uploaded a PR with this

**Comment by alvaroOnCode** [comment]
Still need a hand?

**Comment by d4g0** [comment]
Just uploaded an spanish translation of guides/concepts/ views.md

**Comment by FelixMor** [comment]
Working on /guides/concepts/views

**Comment by FelixMor** [comment]
> Working on /guides/concepts/views

Hi @debs-obrien , I cannot find any guides/concepts/views...this is what I see within the "/guides/concepts/ " folder
![image](https://user-images.githubusercontent.com/37050904/94352316-ee33dc00-0028-11eb-9783-3f93545a4161.png)

**Comment by FelixMor** [comment]
> Great question. I have just added labels so we can filter by label so when adding a pr just add the spanish label and we can see what has been done and what hasn't https://github.com/nuxt/nuxtjs.org/pulls?q=is%3Aopen+is%3Apr+label%3Aspanish
> I think you can go ahead @glpzzz remember you can always submit work as a draft and that way people can also see it is being worked on. There are now a few pages in review and only 3 missing
> 
> * [ ]   /guides/concepts/views
> * [ ]   /guides/directory-structure/modules
> * [ ]   /guides/concepts/static-site-generation

Hi @debs-obrien : I am working on guides/concepts/static-site-generation.md

**Comment by glpzzz** [comment]
@debs-obrien something else to do here?

**Comment by FelixMor** [comment]
> guides/concepts/static-site-generation.md

@debs-obrien Done! I just submitted a pull request: #772 (Translated guides/concepts/static-site-generation.md to Spanish)

**Comment by debs-obrien** [comment]
hey great work everyone. I think we are only requiring a quick review of a few pages and then we are ready for release. If anyone has the time to help with this then I can get it out and featured in our Newsletter 💪
https://github.com/nuxt/nuxtjs.org/pulls?q=is%3Aopen+is%3Apr+label%3Aspanish

**Comment by debs-obrien** [comment]
Well done everyone and thanks for all your help. we are live

https://es.nuxtjs.org/guides/get-started/installation
