### ISSUE TITLE
Configuration > Cache - Page Not Found

### ISSUE THREAD

**Issue by nhterry** [nuxt/nuxtjs.org#56]
https://nuxtjs.org/api/configuration-cache

404
API page not found

Link is on: 
https://nuxtjs.org/examples/cached-components/
and
https://nuxtjs.org/guide/configuration

**Comment by pi0** [comment]
Hi. Thanks for info I will remove that section too. Actually cache is now possible using a module:

https://github.com/nuxt-community/modules/tree/master/modules/component-cache
