### ISSUE TITLE
Horizontal scroll appears on mouse-over the right menu in Guides

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nuxtjs.org#575]
Since the menu items on the right move when you mouse over them, there are some cases where a horiz scroll appears as you move over them.  

My guess is the container needs overflow-x: hidden

https://nuxtjs.org/guides/internals-glossary/context#from
![image](https://user-images.githubusercontent.com/2112282/91220553-f32c0580-e6e1-11ea-8f59-b5307c671247.png)

**Comment by hecktarzuli** [comment]
Should I instead open this in the nuxt/content repo?

**Comment by debs-obrien** [comment]
No. Although the website uses content it is not using content theme like the docs for modules are. So this issue is correct in being related to this project.

**Comment by debs-obrien** [comment]
Thanks @hecktarzuli: https://github.com/nuxt/nuxtjs.org/pull/579
