### ISSUE TITLE
Building fails randomly

### ISSUE THREAD

**Issue by sirtimid** [nuxt/nuxtjs.org#58]
8 out of 10 times bulding fails on server with the following message

npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! auth-routes@ build: `nuxt build`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the auth-routes@ build script 'nuxt build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the auth-routes package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs auth-routes
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls auth-routes
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/example/npm-debug.log

**Comment by pi0** [comment]
Would you please provide full error trace (Or of exists in npm-debug.log) There is not enough details to help. Also do you confirm there are enough RAM and HDD on router server ?

**Comment by sirtimid** [comment]
It's the same error in npm-debug.log. What is considered as enough RAM and HDD? I currently have a digitalocean machine 2GB Memory / 40GB Disk / Ubuntu 16.04.1 x64. Physical RAM being used is usually at 50%, CPU 10%, HDD 50%. When building, memory spikes at 80%.

**Comment by pi0** [comment]
This is wired Resources seem enough! And error still shows nothing. Would you please share repo link? (Also that would be nice opening issues in main repo, this repo is for docs)

**Comment by sirtimid** [comment]
Oh sorry! I didn't realise this is the repo for docs! Unfortunately it is a private project on gitlab, but I 'll try to give more info.

**Comment by sirtimid** [comment]
This is the more detailed error

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle auth-routes@~prebuild: auth-routes@
6 silly lifecycle auth-routes@~prebuild: no script for prebuild, continuing
7 info lifecycle auth-routes@~build: auth-routes@
8 verbose lifecycle auth-routes@~build: unsafe-perm in lifecycle true
9 verbose lifecycle auth-routes@~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/www/example/node_modules/.bin:/root/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle auth-routes@~build: CWD: /var/www/example
11 silly lifecycle auth-routes@~build: Args: [ '-c', 'nuxt build' ]
12 silly lifecycle auth-routes@~build: Returned: code: 137  signal: null
13 info lifecycle auth-routes@~build: Failed to exec build script
14 verbose stack Error: auth-routes@ build: `nuxt build`
14 verbose stack Exit status 137
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid auth-routes@
16 verbose cwd /var/www/example
17 error Linux 4.4.0-38-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
19 error node v6.11.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error auth-routes@ build: `nuxt build`
22 error Exit status 137
23 error Failed at the auth-routes@ build script 'nuxt build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the auth-routes package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     nuxt build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs auth-routes
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls auth-routes
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Atinux** [comment]
@sirtimid i let you post this issue in the appropriate repo if this error persists with the last version of Nuxt.js
