### ISSUE TITLE
kazupon/vue-i18n not working.. 

### ISSUE THREAD

**Issue by jaubut** [nuxt/nuxtjs.org#61]
Hi even fork the official exemple on nuxtjs.org and even this one not working.. Anyone know why ?

**Comment by Atinux** [comment]
Hi @jaubut 

Please check updated example: https://github.com/nuxt/nuxt.js/tree/dev/examples/i18n

**Comment by yshterev** [comment]
@Atinux Live demo link https://i18n.nuxtjs.org/ in https://nuxtjs.org/examples/i18n redirects to https://zeit.co
