### ISSUE TITLE
Languages should never be represented with a national flag

### ISSUE THREAD

**Issue by simnalamburt** [nuxt/nuxtjs.org#62]
<img width="250" alt="2017-09-08 5 45 48" src="https://user-images.githubusercontent.com/4435445/30203622-931cde04-94bd-11e7-8b77-a64d2a2e5350.png">

Languages should never be represented with a national flag.

1. A country with a history of British colonization may still use English as their official language, and using the Union Jack to denote their official language could be offensive.
2. A country may have more than one language in common use, and using the national flag to refer to only one language would mean ignoring the other communities.
3. Using the German national flag to refer to the German language would imply that the Federal Republic of Germany has some kind of language authority, while other German-speaking countries (Austria, Switzterland, etc.) don't.
4. Using national flags is not a scalable approach; Some languages don't have a corresponding flag at all.

Most languages are not one-to-one correspondence with a state. If you need a good way to identify languages, please use the name of them just like [vuejs.org](https://vuejs.org) does so.

<img width="207" alt="2017-09-08 5 58 29" src="https://user-images.githubusercontent.com/4435445/30204198-7bee20f6-94bf-11e7-903a-201468ddee1e.png">

Special thanks to @xtendo-org, for bringing up this problem.

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c59">#c59</a>)</em></sub></div>

**Comment by Atinux** [comment]
@simnalamburt Thank you for bringing this up, we will update this with the new website coming.
