### ISSUE TITLE
Nuxt French Traduction

### ISSUE THREAD

**Issue by Haeresis** [nuxt/nuxtjs.org#63]
Bonjour @Atinux,

Je synchronise les travaux de Vuejs-FR et nous avons terminé Vue, Vuex, Vue Router et Vue Server Renderer. Actuellement il nous reste le chantier Vue Loader a traduire dans l'écosystème officiel.

L'un d'entre nous a évoqué la possibilité de traduire Nuxt, ce qui m'a étonné étant donné (il me semble) que tu es français. Mais effectivement, il n'y a pas de documentation française (visible).

As-tu prévu quelque chose où est ce que nous pouvons nous y mettre ?

L'idée serait de faire une réplique (« fork ») de ce dépôt à l'adresse https://github.com/vuejs-fr/nuxtjs.org

Et d'y mettre le CNAME de https://fr.nuxtjs.org/

Il ne nous resterait ensuite plus qu'à traduire depuis notre dépôt le site.

Chaque semaine, nous ferions une vérification upstream pour mettre à jour notre dépôt et régler les conflits de « changement de traduction » et/ou traduire les « nouvelles traductions ».

Généralement on traduit fichier par fichier avec un ou deux relecteurs pour le chantier initial.

Qu'en dis-tu ?

PS : si une version complètement différente de la doc est envisagé, nous préférons attendre cette version avant de traduire mais si dès maintenant la doc est assez « stable », c'est parti !

**Comment by Haeresis** [comment]
Re @Atinux, je viens de voir sur Twitter que rien n'était en cours.

Reste que nous n'utilisons pas GitLocalize de notre côté après en avoir évoqué la possibilité : 
— https://github.com/vuejs-fr/vuejs.org/issues/64

Pour les raisons suivantes : 
— https://github.com/vuejs/vuejs.org/issues/933#issuecomment-314556475

Notre workflow actuel étant le suivant :
— https://github.com/vuejs-fr/vuejs.org/issues/40

Si tu nous fais confiance pour la traduction avec ce flux on est parti.

**Comment by Haeresis** [comment]
Je viens de jetter un oeil, il semble que le projet est déjà partiellement traduit. Qui s'en occupe ? Vous attendez la traduction complète avant mise en ligne ?

**Comment by Atinux** [comment]
@Haeresis actuellement la personne en charge n'a plus de temps pour continuer malheureusement.

Normalement y a le setup qui n'est pas tres complique sur https://github.com/nuxt/nuxtjs.org et https://github.com/nuxt/docs

Tu as juste besoin d'ajouter dans ton `/etc/hosts`:
```bash
127.0.0.1       fr.nuxt
```

De lancer les 2 serveurs (docs + nuxtjs.org) et d'aller sur http://fr.nuxt:3000

Apres il suffit de modifier les fichiers dans le dossier `fr/`, dis moi si tu as besoin d'aide, ce sera avec grand plaisir !

**Comment by Haeresis** [comment]
Merci @Atinux.

Je viens de faire une relecture du fichier : https://gitlocalize.com/repo/100/fr/en/guide/installation.md
La relecture est là : https://gitlocalize.com/repo/100/fr/review/244/segments

Voici les problèmes que j'ai a adresser à GitLocalise lors de mon essai : 

— Les PR ne ressortent pas sur le projet GitHub, impossible donc d'avoir un workflow de traduction, d'attribuer des relecteurs et de commenter les pens traduit.
— Le « faux » système de rendu ne rend pas comme ce que rendra le site et l'édition passe le markdown en code HTML, hors, pour garder des fichiers de traduction propre, il ne faut pas que cela soit le cas.
— Le système de résolution des conflits ne marche pas

Voici un exemple de review sur un document que nous avons faites à 4 : 
— https://github.com/vuejs-fr/vuejs.org/pull/29

Comme tu peux le constater, on a besoin d'un peu plus d'outil qu'un semblant d'éditeur.

Sur le Fork que nous allons faire de https://github.com/nuxt/docs, nous allons créer une branche working et une branche master. La master sera un mirroir de votre master. Dans notre branche working nous traduisons directement le dossier EN en FR, puis nous le reverssons dans la master chez nous dans le dossier FR. De cette manière, tout changement de la doc EN génère des conflits sur notre base de travail dans working et la documentation peut être maintenue au jour le jour sans connaissance particulière de GitLocalise. Et tout ce que nous faisons, ce sont des PR de notre master vers la votre pour alimenter de traduction à jour votre dépôt officiel.

Si c'est okay pour toi, je souhaiterais faire la relecture des traductions déjà réalisée avec l'équipe Vuejs-FR de cette manière (comme cela a été le cas pour Vuex qui était déjà traduit mais avec pleins de coquilles :) avec l'aide des traducteurs d'origine quand ils le souhaitaient) : 
— https://github.com/vuejs-fr/vuex/issues/1

**Comment by Atinux** [comment]
@Haeresis Ce workflow me semble idéal en effet, je suis d'accord avec toi sur les points negatifs de GitLocalize, le projet n'est pas encore mature.

Est-ce que tu veux que je merge ta PR de GitLocalize avant ?

**Comment by Haeresis** [comment]
Oui ! Je veux bien ;)

**Comment by Haeresis** [comment]
Je t'ai ajouté en membre de Vuejs-FR @Atinux, ce qui nous permettra de te pinguer au besoin dans les issus sur : https://github.com/vuejs-fr/nuxt

J'ai recup les dernières modif et peut tester les trad dans un environnement de dev sur ma machine avec succès.

Dès que tu seras dans la liste des membre de Vuejs-FR je clos cette issue pour continuer nos éventuels échanges là bas (ou ailleurs).

Merci pour ton aide !

**Comment by Atinux** [comment]
Parfait, c'est super carre j'adore :)

Merci beaucoup pour ton aide et ton enthousiasme @Haeresis !

**Comment by Haeresis** [comment]
De mon côté j'ai changé des documents en français dans le dossier EN de working (le fichier `guide/index.md`. Et je relance la commande
— `nodemon --watch *.js --exec 'node api.js'` depuis un dossier `/nuxt/` (qui correspond au projet `docs` en local). 
Ce qui me fait tourner un `http://localhost:4000/`

Puis je lance la commande
— `nuxt start`

Mais le contenu de `http://nuxt:3000/guide` est toujours en anglais

J'ai essayé avec 

— `nuxt build` puis
— `nuxt start`

Bref, je pense que tu pourras me débloquer plus vite.

Soucis de cache ? Par défaut je suis pluguer sur les APIs en ligne (et pas sur `http://localhost:4000`) ?

Du coup j'ai tenté de remplacer
```
return axios.get(`https://docs.api.nuxtjs.org/menu/${lang}/${category}`)
```
du fichier `nuxt.config.js` par
```
return axios.get(`https://localhost:4000/menu/${lang}/${category}`)
```
puis j'ai retesté `nuxt start` ou précédé de `nuxt build` sans succès.

Le contenu de `http://nuxt:3000/guide` reste en anglais. J'ai aussi essayé de vider mon cache navigateur en désespoir de cause :D 

J'ai aussi testé l'alternative `http://localhost:3000/guide` qui me renvoi aussi le contenu anglais.

C'est pas un point bloquant pour la trad, mais je préfère tester le rendu avant merge final.

**Comment by Atinux** [comment]
@Haeresis En fait `nuxt build && nuxt start` sont pour la production et utilise directement le déploiement de `nuxt/docs` (https://github.com/nuxt/nuxtjs.org/blob/master/store/index.js#L41).

En fait, pour bosser en local, il te suffit juste de lancer `npm run dev` dans le dossier `nuxtjs.org/` (equivalent a `nuxt`), du coup, il utilisera `http://localhost:4000` pour recuperer les fichiers markdown.

Peux-tu essayer et me confirmer que c'est bon ?

Merci de ton aide :)

**Comment by Haeresis** [comment]
Tout bon. Merci !
