### ISSUE TITLE
Request: Add a guide on how to set up a Universal/SSR app on Firebase

### ISSUE THREAD

**Issue by dosstx** [nuxt/nuxtjs.org#630]
Currently, there is documentation for how to set up a Nuxt static app on Firebase, but there is none for setting up universal apps. Is it possible someone could add a tutorial on how to set up Nuxt universal apps on Firebase? There are many great tools at Firebase for Nuxt apps!

**Comment by nicodevs** [comment]
@dosstx, what you need is a guide to deploy an universal Nuxt app to [Firebase Hosting](https://firebase.google.com/docs/hosting)?

**Comment by dosstx** [comment]
> @dosstx, what you need is a guide to deploy an universal Nuxt app to [Firebase Hosting](https://firebase.google.com/docs/hosting)?

Yes, to Firebase Hosting. This is different than the regular Google Cloud platform. Right now, you can easily host Nuxt apps on Firebase Hosting if it's a static app, but for SSR/Universal, it seems to be quite different. My use case is that I am building an app using Firebase products (storage, firestore database, etc and it would be nice to also use Firebase to host the app, instead of Heroku).

Thanks to anyone that may know how to get SSR app hosted on Firebase Hosting.

**Comment by debs-obrien** [comment]
Hi @nicodevs can you check the new guides and let me know if that covers what you are looking for and if not perhaps create an issue on that repo so an example or demo can be added. Thanks 
https://firebase.nuxtjs.org/tutorials/ssr

**Comment by dosstx** [comment]
For some reason I never saw this message @debs-obrien , sorry.

To answer your question: No, it doesn't answer what I was asking. I probably was not clear in my attempt to ask the question. What I am looking for is a deployment guide/steps for Firebase Hosting and Nuxt SSR apps: It would go on this page: https://nuxtjs.org/faq/deployment-aws-amplify

P.S> Why is the FAQ page no longer accessible via the NUXTJS site?
