### ISSUE TITLE
document better middleware({ redirect })

### ISSUE THREAD

**Issue by Hulkmaster** [nuxt/nuxtjs.org#643]
### Is your feature request related to a problem? Please describe.

middleware `redirect` with object is not documented

```javascript
      redirect(
        302,
        {
          name: PATH.DEFAULT_SUCCESS,
        },
      );
```
thats example works

### Describe the solution you'd like

better documentation on how to use this https://github.com/nuxt/nuxt.js/blob/b4d3ebf472a8b51b3c8b3f0c0162891987105d8d/packages/vue-app/template/utils.js#L168

### Describe alternatives you've considered

reading https://nuxtjs.org/api/context#-code-redirect-code-em-function-em-
reading source docs

**Comment by kswedberg** [comment]
Looks like the new docs (https://nuxtjs.org/guides/internals-glossary/context#redirect) at least reference the first definition: `redirect([status,] path [, query])`

**Comment by ilejohn-official** [comment]
I wanted to open an issue but decided to search first.

 The `redirect` function doesn't make the `params` property available on the page that is redirected to. Though the query property is available but I would love the `params` property to be available too.  I encountered this in a middleware.

`redirect({ name: 'slug', params: { slug: mySlug } })`
