### ISSUE TITLE
Page describing the various nuxt lifecycle hooks

### ISSUE THREAD

**Issue by uptownhr** [nuxt/nuxtjs.org#65]
1. modules
2. plugins
3. middlewares
4. fetch
5. asyncData

And i know window.onNuxtReady should also be mentioned, but not exactly sure where it goes. I can do a quick write up but please confirm if the order looks good. 

I also noticed that onNuxtReady is not mentioned in the docs. Is this going to be deprecated? 

<div align="right"><sub><em>This feature request is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c53">#c53</a>)</em></sub></div>

**Comment by Atinux** [comment]
@uptownhr actually fetch & asyncData are run in parallel :)

`window.onNuxtReady((app) => ...)` is called after the App is mounted on client-side indeed, it's not going to be deprecated no.

I would love to see a write up for it :)

**Comment by manniL** [comment]
Stale.
