### ISSUE TITLE
Add example for adding components to the default layout

### ISSUE THREAD

**Issue by faheel** [nuxt/nuxtjs.org#656]
Currently, the documentation for the default layout just mentions the following regarding adding more components to the layout:

> You can add more components here such as Navigation, Header, Footer etc. You will need to import them as well as add them to your template.

As a beginner, it took me a while to figure out how to do this properly myself. It would be nice to have an example showing how to add a couple of components to the default layout, such as:

```vue
<template>
  <div>
    <Navbar/>
    <Nuxt/>
    <Footer/>
  </div>
</template>

<script>
  import Navbar from '~/components/navbar.vue'
  import Footer from '~/components/footer.vue'

  export default {
    components: {
      Navbar,
      Footer,
    }
  }
</script>
```

**Comment by debs-obrien** [comment]
Thanks for your feedback. Actually you don't even need the import statements or anything in that script tag. I have added this explanation to the docs: see pr https://github.com/nuxt/nuxtjs.org/pull/658

**Comment by Pooreffects** [comment]
Check out Debbie's YT channel, it contains a fascinating series of Nuxt concepts and workarounds.
https://youtu.be/0ioT7Q7kkVc {layout config}
