### ISSUE TITLE
[DOCS] Double Scrollbar (Guide section)

### ISSUE THREAD

**Issue by nainardev** [nuxt/nuxtjs.org#672]
Right of Platinum Sponsers 
If you cant see, zoom the page layout!
![image](https://user-images.githubusercontent.com/59839368/91551504-e14b9c00-e947-11ea-98f1-6b2a36126be9.png)

**Comment by febrihidayan** [comment]
It can be done by adding a line of code `overflow-y: hidden;`

**Comment by nainardev** [comment]
But, hiding overflow may hide some parts of the last sponsor. What about resizing height on changing viewports? That's way sponsors' logo aren't distorted

**Comment by febrihidayan** [comment]
@nainardev you seem right. Did you mean using the `min-height` property?

**Comment by debs-obrien** [comment]
I am happy for you to make a pr @febrihidayan and then just link the pr to this issue. Just make sure it works for the pages that have long content such as the glossary sections etc. Thanks

**Comment by febrihidayan** [comment]
@debs-obrien I've done it and made a few modifications, but it will impact using the `AffixBlock` component. So another way is to use the prop property to use `overflow` or not to use it. Do you agree with this way or is there another way?

file `AffixBlock.vue`
```vue
<template>
  <div
    class="lg:inset-0 z-90 lg:-mb-0 lg:static lg:h-auto lg:overflow-y-visible lg:pt-0 lg:w-1/4 lg:block"
  >
    <div
      :class="[`lg:scrolling-touch lg:h-auto lg:block lg:relative lg:sticky lg:top-24`, {
        'lg:overflow-y-auto overflow-x-hidden': scroll
      }]"
    >
      <div
        class="flex flex-col sm:flex-row px-4 pt-8 justify-between lg:justify-start lg:flex-col lg:pr-0 lg:pl-8 sticky?lg:max-h-(screen-24)"
      >
        <slot />
      </div>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    scroll: {
      type: Boolean,
      default: true
    }
  }
}
</script>
...
```

file `pages\_section\_slug.vue`
```vue
...
<AffixBlock :scroll="false">
  <SponsorsBlock />
  <AdsBlock :key="$route.params.slug" />
</AffixBlock>
...
```

**Comment by debs-obrien** [comment]
what do you think @bdrtsky

**Comment by bdrtsky** [comment]
We can remove `sticky?lg:max-h-(screen-24)` and it should be fixed

**Comment by febrihidayan** [comment]
@bdrtsky remove `sticky?lg:max-h-(screen-24)` will be affected in the glossary section?

**Comment by nainardev** [comment]
Can you include a CodeSandbox link with that changes?
