### ISSUE TITLE
Example with blog feature

### ISSUE THREAD

**Issue by gregbenner** [nuxt/nuxtjs.org#697]
### Is your feature request related to a problem? Please describe.

I would like an example with more robust blog features like, a sitemap and a feed (xml, rss) and working search, and static generation working

**Comment by garethredfern** [comment]
@debs-obrien I would be happy help and do a write up for this either on the blog or in addition to any docs. Just let me know if that may be of use?

**Comment by debs-obrien** [comment]
hey @garethredfern yes I was just going to add it as a link at bottom of post so people can read it for more info rather than add it to the tutorial which is already quite long and detailed. Thanks. great work on the article.

**Comment by debs-obrien** [comment]
Sitemap added: https://github.com/nuxt/nuxtjs.org/commit/3ac4fa4013ca83208b8eb283ba388f85cae1f642

**Comment by debs-obrien** [comment]
Added these articles: https://github.com/nuxt/nuxtjs.org/pull/850. thanks @garethredfern.

closing this issue
