### ISSUE TITLE
No ability to translate some hardcoded texts

### ISSUE THREAD

**Issue by Alex-Sokolov** [nuxt/nuxtjs.org#7]
Placeholder in search is hardcoded:
https://github.com/nuxt/nuxtjs.org/blob/master/components/Search.vue#L3

"Version" in affix is hardcoded:
https://github.com/nuxt/nuxtjs.org/blob/master/components/Affix.vue#L7

Will be great change that in docs-translations

**Comment by alexchopin** [comment]
Good catch, it's fixed with theses commits [f0f0b23](https://github.com/nuxt/nuxtjs.org/commit/f0f0b231b9d2b775c6552426136cb547494a5b65) and [a64f58d](https://github.com/nuxt/docs/commit/a64f58d235ad5f56f3d9a769823772094f850538).
Thanks

**Comment by Atinux** [comment]
It's also fixed online @Alex-Sokolov 

https://ru.nuxtjs.org/

**Comment by Alex-Sokolov** [comment]
Thanks!
