### ISSUE TITLE
The guide isn't translated in Any Language except English

### ISSUE THREAD

**Issue by twtwtw-gj** [nuxt/nuxtjs.org#703]
---
name: 🚨 Bug report | Bug 提交
about: Report a bug report to help us improve Nuxt.js.
title: 'It isn't translated in Japanese'
labels: 'bug-report'
assignees: ''

---

### Versions

	⁃	Nuxt.js:v2.14.5

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce

access to https://ja.nuxtjs.org/guides/get-started/installation

### What is Expected?

The writing will be written in Japanese.

### What is actually happening?

In English.

**Comment by debs-obrien** [comment]
Thanks for your feedback. The guides section in Japanese will be released once all the pages have been translated that is why we still keep the guide section there in japanese until the translations are finished. Hopefully in a few weeks it will be all translated and it can be released. For the moment the only other language where the guides has been translated is Portuguese. Spanish should be released very soon. Japanese is still a work in progress. see issue: https://github.com/nuxt/nuxtjs.org/issues/544
