### ISSUE TITLE
Nuxtjs Page components are not updated even if the vuex store is updated

### ISSUE THREAD

**Issue by robinlery** [nuxt/nuxtjs.org#75]
I am using nuxtjs for a server side rendering project. I have a REST API from where I would like to update the Vuex store and display the page. [In the nuxtjs documentation for using Vuex store, it mentions using `fetch` api of the pages](https://nuxtjs.org/guide/vuex-store#the-fetch-method). So I am trying to fetch the article list for the API and render the page.

Vuex store:

```
const createStore = () => {
  return new Vuex.Store({
    state: {
      article_list: []
    },
    mutations: {
      updateArticleList (state, payload) {
        state.article_list = payload
        console.log('article list length', state.article_list.length)
      }
    },
    actions: {
      mutateArticleList ({commit}, payload) {
        commit('updateArticleList', payload)
      }
    }
  })
}
```

In the pages/index.vue:

```
<template>
  ...
    <tag-contents v-for="article in $store.state.article_list" :key="article.id"></tag-contents>
  ...
</template>

<script>
  export default {
    ...
    fetch ({store, params}) {
      api.get_articles()
        .then((data) => {
          store.dispatch('mutateArticleList', data)
        })
    },
    created () {
      console.log('index created length', this.$store.state.article_list.length)
    }
  }
</script>
```

On the console I can see that the store's article_list has been updated

`console.log('article list length', state.article_list.length) // 16`

But on the index.vue page, there's no articles. Even on the console of index created method the article_list is 0

`console.log('index created length', this.$store.state.article_list.length) // 0`

What am I missing here? Could you please help me.

**Comment by Atinux** [comment]
Wrong repo
