### ISSUE TITLE
Cloudflare (miss-)configuration

### ISSUE THREAD

**Issue by bivald** [nuxt/nuxtjs.org#76]
Hi,

You'r obviously using Cloudflare (kudos!) but you've done a miss-configuration making it easy to get your origin IP (and show that you'r own Amazon AWS, 54.XXX.XXX.XXX). This is traditionally not a problem unless your using Cloudflare for DDOS protection, which is a great benefit of CF.

You should rename the subdomain that reveals your actual ip (dxxxxxx.nuxtjs.org) or delete it altogether. 

Regards,
Niklas

**Comment by Atinux** [comment]
Hey @bivald 

Thanks but we are actually using zeit.co hosting, so it's not really our issue :)

**Comment by bivald** [comment]
I'll do a Issue with them instead :)
