### ISSUE TITLE
nuxt generate error

### ISSUE THREAD

**Issue by luchanghong** [nuxt/nuxtjs.org#77]
- `npm run dev` is ok

- `npm run generate` got

```
...
Generating routes
...

{ Error: ENOENT: no such file or directory, lstat '/project/dist/index.html'
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/project/dist/index.html' }
```

**Comment by hack2root** [comment]
possibly try nuxt generate in /project folder

**Comment by alexmacarthur** [comment]
I'm getting the same error; can't figure out what might be causing it: 

```
{ Error: ENOENT: no such file or directory, lstat 'blahblahblah/dist/index.html'
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'blahblahblah/dist/index.html' }
```

**Comment by parafox0417** [comment]
Same issue.  The error message seems to be caused by the generation of the route '/' failing.  How do we debug this and see what the real issue is?

**Comment by stevejcox** [comment]
I'm getting the same thing.

On local it works fine, when via CI I get the same error

**Comment by apmontgomery** [comment]
same here.  Mine started when I added the nuxt-apollo module

**Comment by YurikBC** [comment]
This problem are connected to nuxtServerInit usage.
