### ISSUE TITLE
The deployment is currently unavailable.

### ISSUE THREAD

**Issue by anteriovieira** [nuxt/nuxtjs.org#79]
![image](https://user-images.githubusercontent.com/1490347/31830441-f0bdb428-b59e-11e7-833f-21f7c5ca0dd1.png)

**Comment by pi0** [comment]
Hi. Thanks for the report. We will investigate this problem soon.

**Comment by jordanranson** [comment]
Will this be taken care of soon? I need the docs for a deploy I'm supposed to be doing this afternoon, and it looks like a lot of effort to set up the docs locally.

**Comment by pi0** [comment]
Unfortunately, problems are with zeit now: https://twitter.com/zeit_status and out of our control. 

I know this i not be so appreciate but you can always use github to browse markdowns :) https://github.com/nuxt/docs/tree/master/en

**Comment by jordanranson** [comment]
Excellent, thanks. I tried getting the docs API running locally but there are errors. I'll log the errors in the API repo.

**Comment by anteriovieira** [comment]
Solved!
