### ISSUE TITLE
Inconsistent casing in docs for context.isDev

### ISSUE THREAD

**Issue by Govern0r** [nuxt/nuxtjs.org#797]
Very minor fix. See: https://nuxtjs.org/guides/internals-glossary/context#isdev

The heading in the docs for this property says "IsDev" with a capital "I" but the property is really a lowercase "i" (isDev).

I kept trying to use "context.IsDev" in my source because I copied the heading value... I suspect other devs might make this mistake too.

The "isHMR" method's heading has the proper casing (lowercase "I"). 

I suggest updating the heading of the isDev property to have the proper lowercase "i"

**Comment by debs-obrien** [comment]
great, thanks. this is now merged https://github.com/nuxt/nuxtjs.org/pull/806
