### ISSUE TITLE
search bar placement error

### ISSUE THREAD

**Issue by filoret256** [nuxt/nuxtjs.org#8]
Hi there 
some error with changing language 

ru.nuxtjs.org site headers is good - in one line
nuxtjs.org headers are bad, search bar is out of line, can`t change lang

**Comment by alexchopin** [comment]
Hi, can you tell more about which browser do you use and some screenshot if it's possible ?

**Comment by fremdev** [comment]
Hi, I also see the bug in Chrome and Firefox.
![nuxt_search](https://cloud.githubusercontent.com/assets/12509633/22163776/ec9e092e-df5c-11e6-9724-236c418193e5.png)

**Comment by balupton** [comment]
Safari

![screen shot 2017-01-21 at 7 49 31 am](https://cloud.githubusercontent.com/assets/61148/22169328/4be74a02-dfae-11e6-9d05-c97baa6ba73b.png)

**Comment by alexchopin** [comment]
Hi,
It should be fixed now, can you confirm?
Thanks

**Comment by fremdev** [comment]
Yeap, now it's ok.

**Comment by balupton** [comment]
yup fixed
