### ISSUE TITLE
Building fails. Errno 137.

### ISSUE THREAD

**Issue by template01** [nuxt/nuxtjs.org#81]
Hey @Atinux,
Thanks for this nice framework! 

I'm trying to depoly a nuxt-project to a small VPS but it fails in the building/compiling process. It throws an error with the Number 137. Below you'll find the full error log. 

I'm running the latest `nuxt version (rc11)`, `node v6.11.4` and `npm v5.5.1`
Server specs: `1024mb RAM`, `1x 2.40 GHz CPU`, running `Ubuntu 16.04`.

Some catches:

- When I compile the project on other servers of mine or locally there's no problems and the building finishes nicely. 
- When I try to build a 'bare' nuxt-project based on the `community/starter-template` with no extra added content the building process also completes.
- When running the project as a `dev`  server this also builds and gets served properly 

The only other mention of this error is in issue #58. 

Could it be a RAM limit/memory issue?

All the best,
Lasse

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@5.5.1
3 info using node@v6.11.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle uikit-nuxt@1.0.0~prebuild: uikit-nuxt@1.0.0
6 info lifecycle uikit-nuxt@1.0.0~build: uikit-nuxt@1.0.0
7 verbose lifecycle uikit-nuxt@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle uikit-nuxt@1.0.0~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/testing/template-nuxt-03/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle uikit-nuxt@1.0.0~build: CWD: /root/testing/template-nuxt-03
10 silly lifecycle uikit-nuxt@1.0.0~build: Args: [ '-c', 'nuxt build' ]
11 silly lifecycle uikit-nuxt@1.0.0~build: Returned: code: 137  signal: null
12 info lifecycle uikit-nuxt@1.0.0~build: Failed to exec build script
13 verbose stack Error: uikit-nuxt@1.0.0 build: `nuxt build`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid uikit-nuxt@1.0.0
15 verbose cwd /root/testing/template-nuxt-03
16 verbose Linux 2.6.32-042stab125.3
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v6.11.4
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 137
22 error uikit-nuxt@1.0.0 build: `nuxt build`
22 error Exit status 137
23 error Failed at the uikit-nuxt@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```

**Comment by template01** [comment]
So I did a bit more digging. Indeed the server runs out of memory right around the time when the build process fails. However none of the HDD swap-space seems to be used by the build process. Is there a way to throttle the build process?

**Comment by Atinux** [comment]
Could you try to build it with node 8 & the last version of NPM @template01 ?

**Comment by template01** [comment]
Hey @Atinux!
Yes. Node 8 did the trick. Amaze. Guess it handles the build process more effeciently. 
Thanks!

**Comment by do-web** [comment]
I have the same problem:

node v8.9.1
npm  v5.5.1

**Comment by steklopod** [comment]
I have the same problem:
![2019-08-23_11-58-58](https://user-images.githubusercontent.com/29500153/63580401-682fa100-c59d-11e9-8325-ab10381d4999.png)

**Comment by mrtnzagustin** [comment]
Same problem here!!

![image](https://user-images.githubusercontent.com/12588882/66260172-6c9ccb80-e791-11e9-8870-4224053bf5da.png)

**Comment by ppinto20** [comment]
Check if swap is enabled on your server. This usually means that you server isn't really powerful and runs out of memory building the files. I had this problem before and fixed by adding swap on my server, more info: https://linuxize.com/post/how-to-add-swap-space-on-ubuntu-18-04/

**Comment by mrtnzagustin** [comment]
@ppinto20 thanks! i've resized the DigitalOcean droplet to 2gb of ram and the build works properly. Anyway, i will build the app in an alternative pc and upload the neccesary files/container image (like it should be, not? -> build, release, deploy).
Thanks again!!

**Comment by Samuel-Isirima** [comment]
I faced a similar issue with a legacy project that builds with only node v 14.2
I was running the project on a 2GB 1 core intel server running Ubuntu.
All I had to do was add swap memory of 1GB and that solved the problem for me.
