### ISSUE TITLE
Is doc search bar broken?

### ISSUE THREAD

**Issue by larrykkk** [nuxt/nuxtjs.org#817]
Hi, I am using doc (https://nuxtjs.org/) header search bar, but it seem broken.
If using another browser it will working, but just work onece, and then second time i typeing on search bar it is no response,
even i click "enter", the search bar don't have any response.

**Comment by debs-obrien** [comment]
Let me know if you are still having this issue. It seems to be working on my end.

**Comment by larrykkk** [comment]
> Let me know if you are still having this issue. It seems to be working on my end.

The search bar is working now. Thank you.
