### ISSUE TITLE
A little type o

### ISSUE THREAD

**Issue by eruby94** [nuxt/nuxtjs.org#82]
![screen shot 2017-10-24 at 12 18 47 pm](https://user-images.githubusercontent.com/12565404/31955186-a7a885d2-b8b5-11e7-97df-9f7ee6ed2af5.png)

Found with the url: https://nuxtjs.org/api/configuration-loading/

Not difficult to understand, but better not to have it.

Theses should be these

**Comment by Atinux** [comment]
Thanks :)
