### ISSUE TITLE
Make it more clear on what is target 'static' 

### ISSUE THREAD

**Issue by mandaputtra** [nuxt/nuxtjs.org#830]
On the [docs](https://nuxtjs.org/guides/concepts/static-site-generation) there are no guides on how to `target: 'static'`, but the [blog](https://nuxtjs.org/blog/going-full-static/) had more info on how to use it. 

The terminal also make me a bit confused, whether you run `nuxt generate` or `nuxt build` the terminal shows this

![confused terminal](https://user-images.githubusercontent.com/23342943/95778685-d039cd00-0cf2-11eb-87bb-b63bd9396448.png)

The part that make me confuse

```
ℹ Bundling for server and client side                                               01:12:07
ℹ Target: full static 
```

Is running `nuxt generate` still build server and client like SSR does?  Should that terminal information deleted? Or is it actually intended? Why is it?

**Comment by debs-obrien** [comment]
Thanks for your feedback. we are working on improving the terminal messages as can be seen in this pr:https://github.com/nuxt/nuxt.js/pull/8206 and also the documentation as can be seen here: https://github.com/nuxt/nuxtjs.org/pull/844

They should be merged over the next few days. Thanks for your feedback
