### ISSUE TITLE
Dark mode button is broken on main page

### ISSUE THREAD

**Issue by ilijanovic** [nuxt/nuxtjs.org#874]
The dark mode button on the bottom left corner does not work on https://nuxtjs.org/

Clean cache, refresh page and click it. It will work.

Refresh page again. Error appears in the console and the button does not work anymore.

Seems like service worker isnt working correctly

**Comment by ilijanovic** [comment]
@Danondso  i used chrome Version 86.0.4240.75

**Comment by debs-obrien** [comment]
Thanks @ilijanovic we will look into this.

@pi0 seems that service workers are causing issues.

**Comment by febrihidayan** [comment]
Some of the mistakes I found:
- Video does not load
- Cannot change language

It seems that this error is in some language documents only. I don't encounter any errors when using language documents like Français, Español, Português, or Русский. Hope this helps

**Comment by Atinux** [comment]
Can you try a hard refresh to see if it fixes the issue?

**Comment by ilijanovic** [comment]
@Atinux 

Most of the times it works well.  Sometimes after clearing cache / data storage i get this error:

![image](https://user-images.githubusercontent.com/56176036/98080595-f4ae4280-1e75-11eb-86e2-df56f3f94d55.png)

**Comment by ilijanovic** [comment]
@Atinux 

Most of the time it works well. Sometimes if you clear storage / cookies this error appear witch cause the bug:

![err](https://user-images.githubusercontent.com/56176036/98080818-55d61600-1e76-11eb-854b-6901dfd36be6.png)

**Comment by Atinux** [comment]
We are working on a fix at the moment :)

**Comment by Atinux** [comment]
Do you mind trying again?

**Comment by ilijanovic** [comment]
@Atinux sure.

It seems to work. No erros in console!

**Comment by debs-obrien** [comment]
great, closing this issue. let us know if it happens again in the future 😃
