### ISSUE TITLE
UI BUG

### ISSUE THREAD

**Issue by limichange** [nuxt/nuxtjs.org#9]
![image](https://cloud.githubusercontent.com/assets/1947344/22189289/ae4e8300-e156-11e6-9d17-21a64da55a45.png)
![image](https://cloud.githubusercontent.com/assets/1947344/22189296/ba78b2fe-e156-11e6-8c55-eedff8caceaa.png)
![image](https://cloud.githubusercontent.com/assets/1947344/22189308/c88205ee-e156-11e6-8ccd-d984157914bc.png)

**Comment by limichange** [comment]
![image](https://cloud.githubusercontent.com/assets/1947344/22189398/4b2366d2-e157-11e6-9566-9b10d94426aa.png)

**Comment by alexchopin** [comment]
Hi, thanks for the report. It should be fixed now.
