### ISSUE TITLE
the server responded with a status of 500 (TypeError)

### ISSUE THREAD

**Issue by cybibo** [nuxt/nuxtjs.org#90]
> npm run dev

http://nuxt:3000/

[Vue warn]: Error in render function: "TypeError: Cannot read property 'search' of undefined"

found in

---> <NuxtHeaderNavSearch> at components/HeaderNavSearch.vue
       <NuxtHeaderNav> at components/HeaderNav.vue
         <Navbar> at components/Header.vue
           <Default> at layouts/default.vue
             <Root>

**Comment by wwb568109135** [comment]
如上？？

**Comment by Atinux** [comment]
You need to run the docs server too @cybibo (https://github.com/nuxt/docs)
