### ISSUE TITLE
[Docs]: Issue on image in Nuxt Lifecycle

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/nuxtjs.org#903]
The image says that, for the new fetch, we can use `@click="fetch"` but it's `click="$fetch"` 

https://nuxtjs.org/guides/concepts/nuxt-lifecycle#

**Comment by debs-obrien** [comment]
thanks @Barbapapazes. You are right it should be `@click="$fetch"`

@Krutie let me know if we can fix this. thanks

**Comment by Krutie** [comment]
Thanks for pointing out @Barbapapazes 👍 
@debs-obrien I have just made a PR #904 for this.
