### ISSUE TITLE
How to make links from dynamic HTML injected into Vue Template behave like nuxt-links ?

### ISSUE THREAD

**Issue by hvaoc** [nuxt/nuxtjs.org#91]
Some background: 
Building an isomorphic blog engine using Nuxt.js and I have exposed blog template to customers as handlebars template (Don't want to expose Vue template to customers - both for security and simplicity). 

At run time, Handlebars template is translated to html with has links (E.g.: Home, Next, Previous, Pagination). At the moment these links are triggering server side calls (breaking the isomorphic app pattern). How to make these links to behave like nuxt-links ?

In react world - this seem to do this: https://github.com/stevenvachon/handlebars-react

**Comment by Atinux** [comment]
Actually, we have this trick and it works really well, you may want to do something like this too: https://github.com/nuxt/nuxtjs.org/blob/master/components/HtmlParser.vue

**Comment by hvaoc** [comment]
This seem to be working. Thanks @Atinux !!
