### ISSUE TITLE
Changing router base path

### ISSUE THREAD

**Issue by danielnedelcu** [nuxt/nuxtjs.org#914]
The application needs to have its router path dynamically given depending on the directory it lives in.

Scenario:
www.app.com/directoryone
www.app.com/directorytwo

The application runs within this `directoryone` well, but need to have it run under `directorytwo` and currently the base is hard coded
router: {
 base: '/directoryone'
}

Any thoughts on how to pull this off considering nuxt.config is compiled with all of these properties already baked in?

**Comment by debs-obrien** [comment]
cc @pi0

**Comment by Atinux** [comment]
This issue is not related to nuxtjs.org, please file a bug report on github.com/nuxt/nuxt.js
