### ISSUE TITLE
Adding router base documentation for gh-pages deployment

### ISSUE THREAD

**Issue by andiwinata** [nuxt/nuxtjs.org#92]
I just recently tried to deploy nuxt.js to `gh-pages`, there are some pages describing how to do it:

* https://nuxtjs.org/faq/github-pages
* https://nuxtjs.org/guide#static-generated-pre-rendering-
* https://nuxtjs.org/guide/commands#single-page-application-deployment-spa-

Since I don't have any custom domain for my github pages and I'm setting up `gh-pages` for my repository (not user), all the documentations above will give me these type of errors in the page:

* `Failed to load resource: net::ERR_FILE_NOT_FOUND` (local)
* `Failed to load resource (404)...`

Until I found out [this comment](https://github.com/nuxt/nuxt.js/issues/1098#issuecomment-315690246). And turns out I need to add my repo name as the `router.base`, to make sure the path is correct.

So I think it is better if there is a bit documentation for above scenario in the website, so people don't need to search for solution

**Comment by Atinux** [comment]
Noted, if you want to make a PR (for English) to explain a bit more, it will be really awesome @andiwinata

**Comment by andiwinata** [comment]
Created PR https://github.com/nuxt/docs/pull/344
