### ISSUE TITLE
No data on Release Notes

### ISSUE THREAD

**Issue by faahim** [nuxt/nuxtjs.org#941]
Hey, amazing people! 👋 

Thanks for all the great work on Nuxt.js.

I've just got on an old Nuxt.js project that's on v1.0.0 and I'm trying to upgrade to the latest. I wanted to check the changelog and expected I'd find it on the [Release Notes](https://nuxtjs.org/docs/2.x/release-notes) page. But it doesn't seem to show anything other than an empty section at the moment.

I've checked the [release-notes.md](https://github.com/nuxt/nuxtjs.org/blob/master/content/en/guides/release-notes.md) file, and it's empty. Does it suppose to fetch data from the [Nuxt.js's Release Notes](https://github.com/nuxt/nuxt.js/releases/)?

I'm not super sure how it supposed to work, but I'd love to help out with it if I can! 🙂 

I'm not a regular user of Nuxt, so I'm not sure if I'm missing anything obvious. Please pardon me in that case.

Side Note: I was looking for issue guideline before creating this, and was directed to [this page](https://nuxtjs.org/guide/contribution-guide), which 404s. So, really sorry if I'm violating any convention here 😬 

Thanks!

**Comment by febrihidayan** [comment]
@faahim You're right, but the team is currently working on updating the old documentation to the new

**Comment by faahim** [comment]
Ah I see! makes sense 🙂 

Thanks to the team for the amazing work, again! Looking forward to it!

**Comment by debs-obrien** [comment]
this is now fixed. Thanks for your feedback
