### ISSUE TITLE
RuntimeConfig link to guide not working

### ISSUE THREAD

**Issue by memic84** [nuxt/nuxtjs.org#945]
The link in https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-runtime-config

to the runtime config is not working: https://nuxtjs.org/guide/runtime-config

**Comment by febrihidayan** [comment]
@memic84 Currently updating the newer documentation, while the old one is removed. Instead, use a new one

**Comment by debs-obrien** [comment]
Thanks @memic84 
fix: https://github.com/nuxt/nuxtjs.org/pull/949
