### ISSUE TITLE
[Vue warn]: Error in render function: "TypeError: Cannot read property 'search' of undefined"

### ISSUE THREAD

**Issue by kjhatis** [nuxt/nuxtjs.org#95]
nuxt:render Rendering url / +0ms
Error on [nuxtServerInit] action, please run the docs server.
  nuxt:render Data fetching /: 151ms +0ms
[Vue warn]: Error in render function: "TypeError: Cannot read property 'search' of undefined"

found in

---> <NuxtHeaderNavSearch> at components/HeaderNavSearch.vue
       <NuxtHeaderNav> at components/HeaderNav.vue
         <Navbar> at components/Header.vue
           <Default> at layouts/default.vue
             <Root>

**Comment by ArStah** [comment]
Same here

**Comment by Atinux** [comment]
Please read the instructions first: https://github.com/nuxt/nuxtjs.org#developing
