### ISSUE TITLE
Release notes edit link is broken

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxtjs.org#957]
It points to https://github.com/nuxt/nuxtjs.org/blob/master/content/en/guides/release-notes/undefined.md

![Screenshot from 2020-11-06 20-40-14](https://user-images.githubusercontent.com/28706372/98412690-4ae6d580-2070-11eb-8b1f-43ac77640dac.png)

**Comment by debs-obrien** [comment]
emm, I don't think you should be able to edit the release notes. perhaps removing the edit button for this page might be a better solution @danielroe what do you think?

**Comment by danielroe** [comment]
@debs-obrien That's a very good point - agreed!

**Comment by lustremedia** [comment]
Just came across that ... where are the release notes gone?

**Comment by debs-obrien** [comment]
link has now been removed and release notes fixed. thanks for your feedback
