### ISSUE TITLE
Feature request: nuxtjs version on frontpage

### ISSUE THREAD

**Issue by lustremedia** [nuxt/nuxtjs.org#969]
I would love to see the latest nuxtjs version right on the front page, rather than digging any further into the documentation. So one could see if there was a version update or not ... 

Maybe something like that:

![image](https://user-images.githubusercontent.com/1240374/98690977-d52f8200-236d-11eb-89de-d41800aa06a9.png)

**Comment by debs-obrien** [comment]
Thanks for your thoughts. we are working on a full re-design for our website. The version number for now can be found in the docs link or don't forget to sign up for our newsletter, follow us on twitter or discord where we send out info on new releases when they happen.
