### ISSUE TITLE
Extreme slow build

### ISSUE THREAD

**Issue by Reechee88** [nuxt/nuxtjs.org#97]
Hello,

I have a project where I use nuxt.js. The build is extreme slow:

`  nuxt:build Building... +0ms
  nuxt:build App root: /home/ricsi/Projects/frontend/app +0ms
  nuxt:build Generating /home/ricsi/Projects/frontend/app/.nuxt files... +0ms
  nuxt:build Generating files... +39ms
  nuxt:build Generating routes... +8ms
  nuxt:build Building files... +18ms
Build completed in 50.745s

Hash: ccd27d0ade455c7432b9
Version: webpack 3.10.0
Time: 50748ms

Hash: 0942c8c57e1faace9323
Version: webpack 3.10.0
Time: 31730ms
             Asset     Size  Chunks             Chunk Names
server-bundle.json  5.09 MB          [emitted]  
  nuxt:build Building done +1m
`

It is very painful for me. How can I upgrade the speed?

Have a nice day,
Richard

**Comment by dpr989** [comment]
I am also experiencing similarly slow build times I'm dev. It's really slowing down my dev process.

**Comment by Reechee88** [comment]
I have invetigated the issue a lot and it turned out that the scss importing slows down the webpack. I have imported the main.scss in several components. I removed every unnecessary import and moved the styling to the component <style>. Since then, it is blazing fast :)

**Comment by dpr989** [comment]
All my styling is being done in the <style> component and I'm not using scss. My application is pretty small not sure why the build process is so slow.

**Comment by Atinux** [comment]
Should be fixed in `1.0.0`, sadly, we cannot control so much the build time since it's completely Webpack :/
