### ISSUE TITLE
Runtime config CLI option is not documented anymore

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxtjs.org#979]
Hey 👋 

The `--dotenv` CLI option was documented (https://github.com/nuxt/nuxtjs.org/blob/61a15846bc4cfebb812f7acba07c54f2959d474d/content/en/_archives/guide/runtime-config.md#env-support) but with the latest changes the part is missing in the current iteration of the website.

**Comment by debs-obrien** [comment]
can you make a pr to this page to add in what you think needs to be added -
