### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by duurland** [nuxt/nuxtjs.org#988]
https://github.com/nuxt/nuxtjs.org/blob/master/content/en/guides/configuration-glossary/configuration-build.md#templates

> ` [..] you can learn more about using them [here](https://github.com/learn-co-students/javascript-lodash-templates-v-000).`

Returns 404

**Comment by danielroe** [comment]
This has been fixed in dev branch and not yet merged.

**Comment by danielroe** [comment]
@debs-obrien would you like me to open a cherry pick PR to master to merge in these fixes?

**Comment by debs-obrien** [comment]
Thanks @danielroe we will merge everything Monday I believe and then once a week.

**Comment by danielroe** [comment]
This can now be closed.
