### ISSUE TITLE
Logo animation

### ISSUE THREAD

**Issue by MrSunshyne** [nuxt/nuxtjs.org#99]
The current flipX-style animation feels very uninspiring.. unlike nuxtjs. 

Here's a bunch of suggestions : https://twitter.com/__Sun__/status/948552869715693568

You guys think this would be worth a PR ?
  

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxtjs.org/issues/c94">#c94</a>)</em></sub></div>

**Comment by Atinux** [comment]
Ping @alexchopin
